name = "DarkElf"

[orders]

[units."Nightmare Mechanical Cavalry"]
type_ = "Bio, Mechanical Mount, Cavalry"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = ""
race = "DarkElf"
unit_special = ""
assualt_pen = "-2"
cost = "2mp, 4cp, 6xp"
assualt_damage = "-1"
assault_special = "z is equal to the number of normal hits in assault"
name = "Nightmare Mechanical Cavalry"
weapons_input = [ "SMG", "Acid Breath",]
assault_ap = ""
size = "medium"
assault = "3/2/1/1"
members = "2"
assault_deflection = "2z/1z/-/-"
assault_die = "5+/6+/6+/6+/"

[units."Elite Infantry"]
type_ = "Infantry"
filters = [ "weapons", "team",]
assault_deflection_die = "6+"
armor = ""
race = "DarkElf"
unit_special = "Unit base gains Psycic resistance 1"
assualt_pen = "-2"
cost = "1xp to upgrade 2 infantry from one or two unit bases"
assualt_damage = "-2"
assault_special = "flexible deflection die: any deflection result from elites may be choosen to add to assault value instead of deflection"
name = "Elite Infantry"
weapons_input = [ "Rifle",]
assault_ap = ""
size = "medium"
assault = "2/2/2/2"
members = ""
assault_deflection = "3/3/3/3"
assault_die = "5+"

[weapons.Rifle]
type_ = "2 handed infantry weapon"
damage = "-2"
special = ""
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "4"
filters = [ "team",]
assault_mod = ""
cost = ""
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Rifle"
pen = "-2"
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = ""
ap = ""
angle = "*/*/*/*"

[weapons."Head Gun"]
type_ = "Droid weapon"
damage = "-2, +2 (total 0) if penetrating all armor \\ poison[6]"
special = ""
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "3"
filters = [ "team",]
assault_mod = ""
cost = ""
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Head Gun"
pen = ""
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = ""
ap = "1"
angle = "*/*/-/-"

[weapons."Acid Cannon"]
type_ = "Main Tank Gun"
damage = ""
special = "Major Acid"
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "6"
filters = [ "team",]
assault_mod = ""
cost = ""
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Acid Cannon"
pen = ""
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = ""
ap = "1"
angle = "*/-/-/-"

[units.Infantry]
type_ = "Bio, Infantry"
filters = [ "weapons", "team",]
assault_deflection_die = "6+"
armor = ""
race = "DarkElf"
unit_special = ""
assualt_pen = "-2"
cost = "3mp"
assualt_damage = "-2"
assault_special = ""
name = "Infantry"
weapons_input = [ "Rifle",]
assault_ap = ""
size = "medium"
assault = "1/1/1/1"
members = "4"
assault_deflection = "1/1/1/1"
assault_die = "5+"

[units."Mechanical Horse Cavalry"]
type_ = "Bio, Mechanical Mount, Cavalry"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = ""
race = "DarkElf"
unit_special = ""
assualt_pen = "-2"
cost = "2mp, 4cp, 1cp"
assualt_damage = "-1"
assault_special = "z=number of hits in assault"
name = "Mechanical Horse Cavalry"
weapons_input = [ "SMG", "CrossBow",]
assault_ap = ""
size = "medium"
assault = "3/2/1/1"
members = "2"
assault_deflection = "2z/2z/2z/2z"
assault_die = "5+"

[weapons.CrossBow]
type_ = "Infantry and cavalry weapon."
damage = "-2"
special = "Poison[6], minor acid"
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "2"
filters = [ "team",]
assault_mod = ""
cost = "2cp to upgrade one base of infantry"
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "CrossBow"
pen = "-2"
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = "Infantry"
ap = ""
angle = "*/*/*/*"

[weapons."Poison Gas Grenade"]
type_ = "Infantry Misc weapon."
damage = "N.A."
special = "Place a Poison Cload[6](4+) within normal range. "
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "1"
filters = [ "team",]
assault_mod = ""
cost = "1cp to upgrade base"
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Poison Gas Grenade"
pen = "N.A."
assault_ap = ""
orders_gained = [ "- + throw Gas Grenade",]
assault_pen_set_to = ""
requiered_to_buy = "Infantry or Cavalery Base"
ap = "N.A"
angle = "*/*/*/*"

[units."Elite Mechanical Cavalry"]
type_ = "Bio, Mechanical Mount, Cavalry"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = ""
race = "DarkElf"
unit_special = "Good shot: +1 to hit \\ Negates to-hit penalty for shooting while moving fast"
assualt_pen = "-2"
cost = "2mp, 4cp, 4xp"
assualt_damage = "-1"
assault_special = "z is equal to the number of hits in regular assault roll"
name = "Elite Mechanical Cavalry"
weapons_input = [ "SMG", "Crossbow",]
assault_ap = ""
size = "medium"
assault = "4/2/1/1"
members = "2"
assault_deflection = "3z/2z/-/-"
assault_die = "5+/6+/6+/6+"

[units."Queen XXX"]
type_ = "Mechanical, Bio Crew"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = "5/4/2/1"
race = "DarkElf"
unit_special = "Immunity to poison cloads \\ Good shot +1 to hit"
assualt_pen = "-1"
cost = "8ip"
assualt_damage = "-1"
assault_special = "poison[6] \\ Tatcial Retreat: Does not get pinned if losing an assault. May also choose to retreat even if winning the assault. Threat the enemy as winning, but noone gets pinned. The enemy occupies the hex, wether it wants to or not..."
name = "Queen XXX"
weapons_input = [ "Acid-Cannon",]
assault_ap = ""
size = "Large"
assault = "4/2/2/1"
members = "1"
assault_deflection = "2/-/-/-"
assault_die = "5+"

[units."Mechanical Spider"]
type_ = "Mechanical, droid"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = "2/2/2/2"
race = "DarkElf"
unit_special = "Good Shot: +1 to hit\\ All terrain cost 1 movement point to enter"
assualt_pen = ""
cost = "2ip"
assualt_damage = "+0"
assault_special = "Poison[6]"
name = "Mechanical Spider"
weapons_input = [ "Head Gun",]
assault_ap = "2"
size = "medium"
assault = "6/4/2/1"
members = "1"
assault_deflection = "3/1/-/-"
assault_die = "5+"

[weapons."Acid Breath"]
type_ = "Specail Cavalery Breath Weapon"
damage = ""
special = "Fires at everthing within range and angle of fire. \\ Major Acid"
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "1"
filters = [ "team",]
assault_mod = ""
cost = ""
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Acid Breath"
pen = ""
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = ""
ap = ""
angle = "*/-/-/-"

[weapons.SMG]
type_ = "Infantry, cavalry weapon. 1 handed"
damage = "-3"
special = ""
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "3"
filters = [ "team",]
assault_mod = ""
cost = "1cp to upgrade one base of infantry"
orders_lost = [ "aim",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "SMG"
pen = "-3"
assault_ap = ""
orders_gained = [ "fire + fire", "load(5) + -", "",]
assault_pen_set_to = ""
requiered_to_buy = "Infantry"
ap = ""
angle = "*/*/*/*"

[weapons."Enhanced Crossbow"]
type_ = "2 handed infantry weapon"
damage = "-2"
special = "poison[8], minor acid"
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "6"
filters = [ "team",]
assault_mod = ""
cost = "1cp to upgrade weapon of one single elite \\\\ ps! for 2xp and 4cp you may have 4 elites with enhanced crossbows..."
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Enhanced Crossbow"
pen = "-2"
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = "Elite Infantry"
ap = ""
angle = "*/*/*/*"

[weapons.Mortar]
type_ = "Infantry base weapon"
damage = "N.A."
special = "Choose a hex within range and rol a die, at 5+ place a Poison & Acid Cload [8, minor][4+] at target hex. Place a Poison Cload[6]  at all hexes surronding that initial hex\\\\ If you don't roll a 5+, move the target hex the result of the die number of hexes in a random direction from choosen hex.  \\\\ Indirect fire. may use line of sight of any friendly unit on the battle field."
assault_deflection_die_set_to = ""
race = "DarkElf"
range_ = "10"
filters = [ "team",]
assault_mod = ""
cost = "8cp, 4xp"
orders_lost = [ "",]
assault_special = ""
assault_dam_set_to = ""
assault_deflection_mod = ""
name = "Mortar"
pen = "N.A"
assault_ap = ""
orders_gained = [ "",]
assault_pen_set_to = ""
requiered_to_buy = "Infantry base"
ap = "N.A."
angle = "*/*/*/*"

[units."Gigant-Spider Rider"]
type_ = "Bio, Cavalry"
filters = [ "weapons", "team",]
assault_deflection_die = "5+"
armor = ""
race = "DarkElf"
unit_special = "GasMask: immune to poison gas"
assualt_pen = "-2"
cost = "1mp, 3xp"
assualt_damage = "-2"
assault_special = "Poison[12], minor acid, Fear[4]"
name = "Gigant-Spider Rider"
weapons_input = [ "",]
assault_ap = ""
size = "medium"
assault = "6/4/2/1"
members = "2"
assault_deflection = "4/2/-/-"
assault_die = "5+"

[units."Nightmare Mechanical Cavalry".orders]
"Fire(smg)" = [ "Fire + fire", "load(5) + -", "- + load(5)",]
Movement = [ "(fast) F + F + F ", "(fast) F + F + 360^0", "(fast) 360^0 + F + F", "(fast) F + F + F,B", "(fast) F + B + 360^0", "(slow) 360^0 + - 0 -", "(slow) 360^0 + F + 360^0", "(slow) 360^0 + A + F", "(slow) 360^0 + F,B + 360^0", "(stand still) 360^0 + A + F", "(stand still) 360^0 + 360^0 + 360^0",]
"Breath Acid Orders" = [ "- + Breath Acid", "- + -",]

[units."Queen XXX".damage_tables]
"Critical Damage" = [ "1: -1 to-hit, +1 to-be-hit", "2: Rotates right in misc 1 step", "3: rotates left in misc 2 and in misc 3", "4: only stand-stil available", "5: unit is covered in major acid", "6: unit covered in major acid x2",]
"Regular damage" = [ "1-5: Lightly Damaged", "6-8: Crittical Damaged, +1 on all future damage",]
"Lightly Damage" = [ "1-3: Pinned", "4-6: +1 on future damage",]

[units."Gigant-Spider Rider".damage_tables]
"Regular Damage" = [ "2-3: Bleed[4]", "4-6: kill 1 member", "''",]
"Psycic damage" = [ "8+: unit pinned",]

[units."Elite Mechanical Cavalry".orders]
"Fire(smg)" = [ "fire + fire", "- + load(5)", "load(5) + -",]
Movement = [ "(fast) F + F + F ", "(fast) F + F + 360^0", "(fast) 360^0 + F + F", "(fast) F + F + F,B", "(fast) F + B + 360^0", "(slow) 360^0 + - 0 -", "(slow) 360^0 + F + 360^0", "(slow) 360^0 + A + F", "(slow) 360^0 + F,B + 360^0", "(stand still) 360^0 + A + F", "(stand still) 360^0 + 360^0 + 360^0",]
"Fire crossbow" = [ "- + fire", "- + load", "- + aim",]

[units."Queen XXX".orders]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + F + -", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow) F + - + -", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "R+ F + -", "L+ F + -",]
"Fire Orders" = [ "(stand still and slow) - + load", "(stand still and slow) - + aim", "(stand still, slow and fast) - + fire", "(stand still, slow and fast) - + Release Poison Cload[12](4+)",]

[units."Mechanical Spider".orders]
"Fire " = [ "- + Fire", "- + Load", "- + Aim",]
Movement = [ "(slow) 360^0 + F + 360^0", "(slow) 360^0 + 360^o + 360^0",]

[units."Nightmare Mechanical Cavalry".damage_tables]
"Regular Damage" = [ "2-3: +1 on future damage", "4-6: Destroy 1 memeber", "7+ : Destroy 1 member, roll on psycic damage",]
"Psycic damage" = [ "6+: unit pinned",]

[units.Infantry.damage_tables]
"Psycic Damage" = [ "4+ Unit base pinned",]
"Regular damage" = [ "0-6: kill 1 member", "7-8: kill 1 member, psycic damage[d6]", "9+ Kill all 4 members",]

[units."Elite Infantry".damage_tables]
"" = [ "",]

[units."Gigant-Spider Rider".orders]
Movement = [ "(slow) 360^0 + F + 360^0", "(slow) 360^0 + 360^0 + 360^0",]

[units.Infantry.orders]
"" = [ "",]

[units."Elite Infantry".orders]
"" = [ "",]

[units."Mechanical Spider".damage_tables]
"Regular Damage" = [ "1-3: Lightly damaged[d6]", "4-6: Heavily Damage, +1 on future damage", "7: Destroyed",]
"Heavy Damage" = [ "1: +1 for future damage", "2: -1 to-hit, +1 to-be-hit", "3: Cannot move", "4: Cannot rotate", "5: Roll on Lightly damage table 3 times", "6: Fire",]
"Lightly Damage" = [ "1-2: unit pinned", "3-4: +1 on future damage", "5-6: -1/-1/-1/-1 to all assaults and assulat deflection values (cumulative, minimum 0)",]

[units."Mechanical Horse Cavalry".orders]
Movement = [ "(fast) F + F + F ", "(fast) F + F + 360^0", "(fast) 360^0 + F + F", "(fast) F + F + F,B", "(fast) F + B + 360^0", "(slow) 360^0 + - 0 -", "(slow) 360^0 + F + 360^0", "(slow) 360^0 + A + F", "(slow) 360^0 + F,B + 360^0", "(stand still) 360^0 + A + F", "(stand still) 360^0 + 360^0 + 360^0",]
Fire = [ "fire(smg) + fire(smg)", "load(5)(smg), + - ", "- + fire (crossbow)", "- + load (crossbow) (stand still, slow only",]

[units."Elite Mechanical Cavalry".damage_tables]
"" = [ "",]

[units."Mechanical Horse Cavalry".damage_tables]
"Regular Damage" = [ "2-3: +1 on future damage", "4-6: Kill 1 member", "7+: Destroy 1 member, roll on psycic damage",]
"Psycic Damage" = [ "5+: unit pinned",]
