name = "DarkElf"

[orders]

[units."Mechanical Spider"]
assault = "6/4/2/1"
type_ = "Mechanical, droid"
assault_special = "Poison[6]"
unit_special = "Good Shot: +1 to hit\\ All terrain cost 1 movement point to enter"
filters = [ "weapons", "team",]
assualt_damage = "+0"
weapons_input = [ "Head Gun",]
assault_die = "5+"
members = "1"
assualt_pen = ""
assault_deflection_die = "5+"
cost = "2ip"
size = "medium"
armor = "2/2/2/2"
assault_ap = "2"
assault_deflection = "3/1/-/-"
name = "Mechanical Spider"
race = "DarkElf"

[units."Elite Infantry"]
assault = "2/2/2/2"
type_ = "Infantry"
assault_special = "flexible deflection die: any deflection result from elites may be choosen to add to assault value instead of deflection"
unit_special = "Unit base gains Psycic resistance 1"
filters = [ "weapons", "team",]
assualt_damage = "-2"
weapons_input = [ "Rifle",]
assault_die = "5+"
members = ""
assualt_pen = "-2"
assault_deflection_die = "6+"
cost = "1xp to upgrade 2 infantry from one or two unit bases"
size = "medium"
armor = ""
assault_ap = ""
assault_deflection = "3/3/3/3"
name = "Elite Infantry"
race = "DarkElf"

[weapons.CrossBow]
special = "Poison[6], minor acid"
pen = "-2"
filters = [ "team",]
assault_deflection_die_set_to = ""
range_ = "2"
cost = "2cp to upgrade one base of infantry"
assault_dam_set_to = ""
orders_lost = [ "",]
race = "DarkElf"
assault_mod = ""
angle = "*/*/*/*"
assault_deflection_mod = ""
ap = ""
assault_special = ""
requiered_to_buy = "Infantry"
assault_pen_set_to = ""
orders_gained = [ "",]
name = "CrossBow"
damage = "-2"
type_ = "Infantry and cavalry weapon."
assault_ap = ""

[weapons.Rifle]
special = ""
pen = "-2"
filters = [ "team",]
assault_deflection_die_set_to = ""
range_ = "4"
cost = ""
assault_dam_set_to = ""
orders_lost = [ "",]
race = "DarkElf"
assault_mod = ""
angle = "*/*/*/*"
assault_deflection_mod = ""
ap = ""
assault_special = ""
requiered_to_buy = ""
assault_pen_set_to = ""
orders_gained = [ "",]
name = "Rifle"
damage = "-2"
type_ = "2 handed infantry weapon"
assault_ap = ""

[units."Mechanical Horse Cavalry"]
assault = "3/2/1/1"
type_ = "Bio, Mechanical Mount, Cavalry"
assault_special = "z=number of hits in assault"
unit_special = ""
filters = [ "weapons", "team",]
assualt_damage = "-1"
weapons_input = [ "SMG", "CrossBow",]
assault_die = "5+"
members = "2"
assualt_pen = "-2"
assault_deflection_die = "5+"
cost = "2mp, 4cp, 1cp"
size = "medium"
armor = ""
assault_ap = ""
assault_deflection = "2z/2z/2z/2z"
name = "Mechanical Horse Cavalry"
race = "DarkElf"

[weapons.SMG]
special = ""
pen = "-3"
filters = [ "team",]
assault_deflection_die_set_to = ""
range_ = "3"
cost = "1cp to upgrade one base of infantry"
assault_dam_set_to = ""
orders_lost = [ "aim",]
race = "DarkElf"
assault_mod = ""
angle = "*/*/*/*"
assault_deflection_mod = ""
ap = ""
assault_special = ""
requiered_to_buy = "Infantry"
assault_pen_set_to = ""
orders_gained = [ "fire + fire", "load(5) + -", "",]
name = "SMG"
damage = "-3"
type_ = "Infantry, cavalry weapon. 1 handed"
assault_ap = ""

[weapons."Head Gun"]
special = ""
pen = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
range_ = "3"
cost = ""
assault_dam_set_to = ""
orders_lost = [ "",]
race = "DarkElf"
assault_mod = ""
angle = "*/*/-/-"
assault_deflection_mod = ""
ap = "1"
assault_special = ""
requiered_to_buy = ""
assault_pen_set_to = ""
orders_gained = [ "",]
name = "Head Gun"
damage = "-2, +2 (total 0) if penetrating all armor \\ poison[6]"
type_ = "Droid weapon"
assault_ap = ""

[units.Infantry]
assault = "1/1/1/1"
type_ = "Bio, Infantry"
assault_special = ""
unit_special = ""
filters = [ "weapons", "team",]
assualt_damage = "-2"
weapons_input = [ "Rifle",]
assault_die = "5+"
members = "4"
assualt_pen = "-2"
assault_deflection_die = "6+"
cost = "3mp"
size = "medium"
armor = ""
assault_ap = ""
assault_deflection = "1/1/1/1"
name = "Infantry"
race = "DarkElf"

[units."Elite Infantry".damage_tables]
"" = [ "",]

[units.Infantry.damage_tables]
"Regular damage" = [ "0-6: kill 1 member", "7-8: kill 1 member, psycic damage[d6]", "9+ Kill all 4 members",]
"Psycic Damage" = [ "4+ Unit base pinned",]

[units."Elite Infantry".orders]
"" = [ "",]

[units."Mechanical Spider".damage_tables]
"Heavy Damage" = [ "1: +1 for future damage", "2: -1 to-hit, +1 to-be-hit", "3: Cannot move", "4: Cannot rotate", "5: Roll on Lightly damage table 3 times", "6: Fire",]
"Regular Damage" = [ "1-3: Lightly damaged[d6]", "4-6: Heavily Damage, +1 on future damage", "7: Destroyed",]
"Lightly Damage" = [ "1-2: unit pinned", "3-4: +1 on future damage", "5-6: -1/-1/-1/-1 to all assaults and assulat deflection values (cumulative, minimum 0)",]

[units."Mechanical Horse Cavalry".orders]
Fire = [ "fire(smg) + fire(smg)", "load(5)(smg), + - ", "- + fire (crossbow)", "- + load (crossbow) (stand still, slow only",]
Movement = [ "(fast) F + F + F ", "(fast) F + F + 360^0", "(fast) 360^0 + F + F", "(fast) F + F + F,B", "(fast) F + B + 360^0", "(slow) 360^0 + - 0 -", "(slow) 360^0 + F + 360^0", "(slow) 360^0 + A + F", "(slow) 360^0 + F,B + 360^0", "(stand still) 360^0 + A + F", "(stand still) 360^0 + 360^0 + 360^0",]

[units."Mechanical Horse Cavalry".damage_tables]
"Psycic Damage" = [ "5+: unit pinned",]
"Regular Damage" = [ "2-3: +1 on future damage", "4-6: Kill 1 member", "7+: Destroy 1 member, roll on psycic damage",]

[units."Mechanical Spider".orders]
"Fire " = [ "- + Fire", "- + Load", "- + Aim",]
Movement = [ "(slow) 360^0 + F + 360^0", "(slow) 360^0 + 360^o + 360^0",]

[units.Infantry.orders]
"" = [ "",]
