name = "Dwarf"

[orders]

[units."Elite Dwarven Infantry"]
size = "medium"
filters = [ "weapons", "team",]
name = "Elite Dwarven Infantry"
assualt_damage = "-2"
assault_die = "4+/5+/5+/6+"
assault_deflection_die = ""
armor = ""
assault_special = ""
weapons_input = [ "Dwarven Musket",]
cost = "1xp to replace up too 2 regular infantry from one or two unit bases"
assault_deflection = "1/-/-/-"
assualt_pen = "-2"
race = "Dwarf"
members = ""
assault = "2/2/1/1/"
type_ = "Bio"
unit_special = "Good shot: +1 to hit. \\ -2 to psycic damage taken \\ Poison Resistance 2 \\ Fire Resistance 1"

[units."Assault Bots"]
size = "medium"
filters = [ "weapons", "team",]
name = "Assault Bots"
assualt_damage = "2AP"
assault_die = "4+/5+/5+/6+/"
assault_deflection_die = "5+/-/-/-"
armor = "2/2/2/2"
assault_special = ""
weapons_input = [ "",]
cost = "3ip, 6xp"
assault_deflection = "1/-/-/-"
assualt_pen = "+0"
race = "Dwarf"
members = "4"
assault = "3/3/3/3"
type_ = "Mechanical"
unit_special = "Immune to all pinning effects."

[weapons."Super Blaster"]
name = "Super Blaster"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = "4"
filters = [ "team",]
range_ = "3"
angle = "*/*/*/*"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = ""
cost = "4cp to give this weapon to one unit"
race = "Dwarf"
type_ = "2 handed special infantry weapon."
damage = "+2"
assault_special = ""
requiered_to_buy = "Elite SteamPowerArmor"

[units."Tamed Balrog"]
size = "Huge, +1 to be hit"
filters = [ "weapons", "team",]
name = "Tamed Balrog"
assualt_damage = "AP 3"
assault_die = "2+"
orders = [ "slow", "Whip", "",]
assault_deflection_die = ""
armor = "3/2/2/1"
assault_special = "Fire"
weapons_input = [ "Flaming Whip",]
cost = "12xp"
assault_deflection = ""
assualt_pen = ""
race = "Dwarf"
members = "1"
assault = "6/4/3/2"
type_ = "Bio, Monster"
unit_special = "Poison Resistance :4 \\ Fire Resistance 12 \\ Terror[8][range=2]"

[weapons."Heavy SMG"]
name = "Heavy SMG"
orders_lost = [ "aim (threat aim as fire)",]
assault_dam_set_to = ""
special = "Unlimited Ammo \\\\ fires 3 shots (at same enemy unit base) per fire. \\\\ Threat any aim and load the unit base get as fire orders instead."
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = ""
filters = [ "team",]
range_ = "3"
angle = "*/*/*/*"
orders_gained = [ "fire + fire",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = "-2"
cost = "4cp"
race = "Dwarf"
type_ = "2 handed special infantry weapon"
damage = "-2"
assault_special = ""
requiered_to_buy = "Elite SteamPowerArmor"

[weapons."Big Blaster"]
name = "Big Blaster"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = "3"
filters = [ "team",]
range_ = "2"
angle = "*/*/*/*"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = ""
cost = "4cp to give one infantry base an alternative weapon"
race = "Dwarf"
type_ = "Infantry Base weapon."
damage = "+1"
assault_special = ""
requiered_to_buy = "Infantry"

[weapons."BIG AT-gun"]
name = "BIG AT-gun"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = "5"
filters = [ "team",]
range_ = "6"
angle = "*/-/-/-"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = ""
cost = ""
race = "Dwarf"
type_ = ""
damage = "+1"
assault_special = ""
requiered_to_buy = ""

[units.SteamPowerArmor]
size = "medium"
filters = [ "weapons", "team",]
name = "SteamPowerArmor"
assualt_damage = "-1"
assault_die = "4+/5+/5+/6+"
assault_deflection_die = ""
armor = "1/1/1/1"
assault_special = ""
weapons_input = [ "Heavy Musket",]
cost = "2mp, 1ip, 2cp"
assault_deflection = ""
assualt_pen = "-1"
race = "Dwarf"
members = "4"
assault = "3/3/3/3"
type_ = "Bio"
unit_special = "Poison resistance 4\\ Fire reistance 2"

[units."Elite SteamPowerArmor"]
size = "medium"
filters = [ "weapons", "team",]
name = "Elite SteamPowerArmor"
assualt_damage = "-1"
assault_die = "4+/5+/5+/6+"
orders = [ "",]
assault_deflection_die = ""
armor = "1/1/1/1"
assault_special = ""
weapons_input = [ "Heavy Musket",]
cost = "4xp to replace one regular SteamPowerArmor member with an elite"
assault_deflection = "2/2/1/1"
assualt_pen = "-1"
race = "Dwarf"
members = ""
assault = "3/3/3/3"
type_ = "Bio"
unit_special = "Unit base gains 1 psycic resistance. \\ Poison Resistance 4 \\ Fire Resistance 2"

[weapons."Musket With Spring Loaded Axe"]
name = "Musket With Spring Loaded Axe"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = "+1/+1/+1/+1"
assault_ap = ""
ap = ""
filters = [ "team",]
range_ = "3"
angle = "*/*/*/*"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = "-2"
cost = "1cp to replace all infantry weapons of one unit base."
race = "Dwarf"
type_ = "2 handed infantry weapon"
damage = "-2"
assault_special = ""
requiered_to_buy = "Infantry"

[weapons."Flaming Whip"]
name = "Flaming Whip"
orders_lost = [ "",]
assault_dam_set_to = ""
special = "Fire"
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = "1"
filters = [ "team",]
range_ = "1"
angle = "*/*/-/-"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = ""
cost = ""
race = "Dwarf"
type_ = "specail unit weapon"
damage = ""
assault_special = ""
requiered_to_buy = ""

[weapons.Musket]
name = "Musket"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = ""
filters = [ "team",]
range_ = "3"
angle = "*/*/*/*"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = "-2"
cost = ""
race = "Dwarf"
type_ = "2 handed infantry weapon"
damage = "-2"
assault_special = ""
requiered_to_buy = ""

[weapons.Blast_sticks]
name = "Blast_sticks"
orders_lost = [ "",]
assault_dam_set_to = "+1"
special = ""
assault_pen_set_to = "0"
assault_mod = ""
assault_ap = ""
ap = ""
filters = [ "team",]
range_ = ""
angle = ""
orders_gained = [ "",]
assault_deflection_die_set_to = "4+/-/-/-"
assault_deflection_mod = "+1/-/-/-"
pen = ""
cost = "1cp to upgrade all weapons of one infantry base"
race = "Dwarf"
type_ = "2 handed infantry weapon"
damage = ""
assault_special = ""
requiered_to_buy = "Infantry"

[weapons.Heavy_Musket]
name = "Heavy_Musket"
orders_lost = [ "",]
assault_dam_set_to = ""
special = ""
assault_pen_set_to = ""
assault_mod = ""
assault_ap = ""
ap = ""
filters = [ "team",]
range_ = "3"
angle = "*/*/*/*"
orders_gained = [ "",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
pen = "-1"
cost = "1cp to replace weapon for one infantry base"
race = "Dwarf"
type_ = "2 handed infantry weapon"
damage = "-1"
assault_special = ""
requiered_to_buy = "Infantry"

[units."Dwarf Infantry"]
size = "medium"
filters = [ "weapons", "team",]
name = "Dwarf Infantry"
assualt_damage = "-2"
assault_die = "4+/5+/5+/6+"
assault_deflection_die = ""
armor = ""
assault_special = ""
weapons_input = [ "Dwarven Musket",]
cost = "2mp"
assault_deflection = ""
assualt_pen = "-2"
race = "Dwarf"
members = "4"
assault = "1/1/1/1"
type_ = "Bio"
unit_special = "Poison Resistance 2 \\ Fire Resistance 1"

[units."Dwarven AT-gun"]
size = "Large"
filters = [ "weapons", "team",]
name = "Dwarven AT-gun"
assualt_damage = "-2"
assault_die = "6+/6+/6+/6+"
orders = [ "Rest", "Stand-Still", "",]
assault_deflection_die = ""
armor = "2/-/-/-"
assault_special = ""
weapons_input = [ "BIG AT-gun",]
cost = "5cp, 3xp"
assault_deflection = ""
assualt_pen = "-2"
race = "Dwarf"
members = "1AT-gun, 4 crew"
assault = "1/1/1/1"
type_ = "Bio"
unit_special = "Poison Resistance 2 \\ Fire resistance 1"

[units."Dwarven AT-gun".damage_tables]
"Psycic damage" = [ "4+: unit base pinned",]
"Regular Damage" = [ "1-6: kill 1 crew", "7-8: kill 1 crew, psycic damage[6]", "9+: unit destroied ", "Is destroied if all 4 crew are destroied",]

[units."Elite Dwarven Infantry".orders]
"" = [ "",]

[units.SteamPowerArmor.orders]
"Main Orders" = [ "(slow) 360^0 + F + 360^0", "360^0 + 360^0 + 360^0", "Fire + -", "aim + - ", "load + -",]

[units."Dwarf Infantry".damage_tables]
"Psycic Damage" = [ "4+: pinned",]
"Regular Damage" = [ "1-5: kill 1 member", "6-9: kill 1 member, roll on psycic damage[d6]", "10: kill all 4 members",]

[units.SteamPowerArmor.damage_tables]
"Psycic damage" = [ "5+: unit base pinned",]
"Regular Damage" = [ "1-5: 1 member killed", "6-9: 1 member killed, roll on psycic damage[d6]", "10+: all 4 members killed",]

[units."Assault Bots".orders]
Slow = [ "360^0 + F + 360^0",]

[units."Elite Dwarven Infantry".damage_tables]
"" = [ "",]

[units."Dwarf Infantry".orders]
"Main Orders" = [ "(slow) 360^0 + F + 360^0", "360^0 + 360^0 + 360^0", "Fire + -", "aim + - ", "load + -",]

[units."Tamed Balrog".damage_tables]
"Regular Damage" = [ "1-8: +1 on future damage", "9-10: +2 on future damage \\ Assault -1/-1/-1/-1 \\ looses terror", "11-12: +3 on future damage \\ Assault -1/-1/-1/-1 \\ Looses Terror \\ Pinned", "13: Destroied/killed",]

[units."Assault Bots".damage_tables]
"Regular Damage" = [ "1-6: +1 on future damage", "7+ : kill 1 memeber",]

[units."Elite SteamPowerArmor".damage_tables]
"" = [ "",]
