name = "Elf"

[units."VelociRaptor Riders"]
assault_special = "poison[4], Cunning Assault[1 for 3]"
size = "medium"
members = "2"
race = "Elf"
assault_deflection = "1/-/-/-"
assault_deflection_die = "5+"
armor = ""
assault = "3/2/2/1"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Poison Resistance[2]"
assault_pen = "-2"
type_ = "Bio, Cavalry"
weapons_input = [ "SMG", "Twin Guns",]
assault_ap = ""
name = "VelociRaptor Riders"
cost = "2mp, 4cp, 2xp"
assault_damage = "d6-2"

[units."Sniper Tank"]
assault_special = "Fear(6)"
size = "Large"
members = "1"
race = "Elf"
assault_deflection = "2/-/-/-"
assault_deflection_die = "5+"
armor = "4/3/3/2"
assault = "4/3/3/2"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Forrester: moving through forrest cost 1 point \\\\ Camuflage[forrest] -1 to-be-hit\\\\ "
assault_pen = "-1"
type_ = "Mechanical, Bio crew Tank"
weapons_input = [ "Calibrated Gun", "Sniper rifle",]
assault_ap = ""
name = "Sniper Tank"
cost = "8ip"
assault_damage = "d6-1"

[weapons.Grenade]
assault_ap = ""
required_to_buy = ""
angle = "*/*/*/*"
orders_lost = [ "",]
special = "Area(5+). May target anyone within normal range. (including 0 if flying and sharing a hex with an enemy)"
ap = "2"
name = "Grenade"
cost = ""
type_ = "Special Cavalery misc weapon. "
assault_special = ""
range_ = "1"
damage = "d6"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons.SMG]
assault_ap = ""
required_to_buy = "infantry, Elk Cavalery, Eagle Rider"
angle = "*/*/*/*"
orders_lost = [ "aim + -", "- + aim",]
special = ""
ap = ""
name = "SMG"
cost = "1cp to upgrade all weapons on all units an unit base"
type_ = "2 handed infantry weapon"
assault_special = ""
range_ = "3"
damage = "d6-3"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "(stand-still, slow, fast) fire(smg) + fire(smg)", "(stand-still, slow) load(5) + -",]
template = "r"
pen = "-3"
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units.Infantry]
assault_special = "Cunning Assault[1 for 2]"
size = "medium"
members = "4"
race = "Elf"
assault_deflection = ""
assault_deflection_die = ""
armor = ""
assault = "1/1/1/1"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Take Cover[stand-still][-2]"
assault_pen = "-2"
type_ = "Bio, Infantry"
weapons_input = [ "Rifle",]
assault_ap = ""
name = "Infantry"
cost = "3mp"
assault_damage = "d6-2"

[weapons."Gattle Gun"]
assault_ap = ""
required_to_buy = ""
angle = "*/*/-/-"
orders_lost = [ "",]
special = "May load up to 5 shots."
ap = "0"
name = "Gattle Gun"
cost = ""
type_ = "Vehicle mounted gun."
assault_special = ""
range_ = "3"
damage = "-2, +2 when penetrating all armor (total 0)"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons."Small grenade"]
assault_ap = ""
required_to_buy = "Infantry"
angle = "*/*/*/*"
orders_lost = [ "",]
special = "Area(6+)"
ap = "1"
name = "Small grenade"
cost = "1cp to give all members access to this weapon"
type_ = "Infantry misc weapon."
assault_special = ""
range_ = "1"
damage = "d6"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "(stand-still, slow, fast) - + throw grenade",]
template = "r"
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons."Twin Guns"]
assault_ap = ""
required_to_buy = ""
angle = "*/-/-/-"
orders_lost = [ "",]
special = "x2 shots per shot"
ap = "1"
name = "Twin Guns"
cost = ""
type_ = "Special cavalry weapon"
assault_special = ""
range_ = "3"
damage = "d6"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units."Eagle Rider"]
assault_special = "Find weakest points: in assault always uses armor from optimal angle. Cunning Assault[1 for 3]"
size = "medium"
members = "1"
race = "Elf"
assault_deflection = "2/2/2/1"
assault_deflection_die = "3+"
armor = "1/1/1/1"
assault = "6/6/6/4"
filters = [ "weapons", "team",]
assault_die = "3+"
unit_special = "If in the air, it may choose to assault if entering same hex as an enemy. If so, regardless of the outcome, the eagle lands. The following round the orders is replaced by the default if illegal. \\\\ In chase, the eagle may choose to land for assault if it wishes. \\\\ Good Shot[At-Rifle] +1 to hit"
assault_pen = "-1"
type_ = "Bio, Flying, Cavalery"
weapons_input = [ "AT-rifle", "Grenade",]
assault_ap = ""
name = "Eagle Rider"
cost = "1mp, 4xp"
assault_damage = "d6-1"

[weapons."Elk Bazooka"]
assault_ap = ""
required_to_buy = ""
angle = "*/-/-/-"
orders_lost = [ "",]
special = "The other unit in the unit base may threat any fire orders as throw."
ap = "3"
name = "Elk Bazooka"
cost = "4cp to give 1 elk cavalry 1 bazooka"
type_ = "2 handed Special cavalery weapon."
assault_special = ""
range_ = "3"
damage = "d6"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "+ - fire", "+ - aim", "+ - load",]
template = "r"
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units."Elite VelociRaptor Riders"]
assault_special = "Poison[4], Cunning Assault[1 for 3]"
size = "medium"
members = "2"
race = "Elf"
assault_deflection = "2/-/-/-"
assault_deflection_die = "5+"
armor = ""
assault = "4/2/2/1"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Poison Resistance[2], good shot: +1 to hit"
assault_pen = "-2"
type_ = "Bio, Cavalery"
weapons_input = [ "SMG", "Twin Guns",]
assault_ap = ""
name = "Elite VelociRaptor Riders"
cost = "1xp to upgrade 2 velociraptor riders from same base"
assault_damage = "d6-2"

[weapons."Sniper rifle"]
assault_ap = ""
required_to_buy = "Elite Infantry"
angle = "*/-/-/-"
orders_lost = [ "",]
special = "Improves aim: +4 to hit, +2 to dam\\\\ May choose which unit in a unit base to kill if it kills 1 (or more) members."
ap = ""
name = "Sniper rifle"
cost = "4cp to upgrade weapon of 1 single elite unit"
type_ = "2 handed infantry weapon"
assault_special = ""
range_ = "8"
damage = "d6-1"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = "r"
pen = "-1"
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons.Rifle]
assault_ap = ""
required_to_buy = ""
angle = "*/*/*/*"
orders_lost = [ "",]
special = ""
ap = ""
name = "Rifle"
cost = ""
type_ = "2 handed infantry weapon"
assault_special = ""
range_ = "5"
damage = "d6-2"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = "-2"
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons."Calibrated Gun"]
assault_ap = ""
required_to_buy = ""
angle = "*/-/-/-"
orders_lost = [ "",]
special = "Armor penetration not reduced with distance"
ap = "2"
name = "Calibrated Gun"
cost = ""
type_ = "Tank gun"
assault_special = ""
range_ = "6"
damage = "d6+3 to damage if a natural 6 is rolled for to-hit, +3 to damage if pentrating all armor"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units.E34]
assault_special = "Fear(6)"
size = "Large"
members = "1"
race = "Elf"
assault_deflection = "2/-/-/-"
assault_deflection_die = "5+"
armor = "4/3/3/2"
assault = "4/3/3/2"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Forrester: moving through forrest cost 1 point (not 2)"
assault_pen = "-1"
type_ = "Mechanical, Bio Crew, Tank"
weapons_input = [ "Main Tank Gun",]
assault_ap = ""
name = "E34"
cost = "6ip"
assault_damage = "d6-1"

[weapons.MiniGun]
assault_ap = ""
required_to_buy = ""
angle = "*/*/*/*"
orders_lost = [ "",]
special = "Fire once at all enemy units within range and within one angle of fire \\\\ If aim, use focus fire, roll 6 dice at same unit base"
ap = ""
name = "MiniGun"
cost = ""
type_ = "Special Cavalry weapon"
assault_special = ""
range_ = "2"
damage = "d6-1"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = "-1"
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[weapons.AT-rifle]
assault_ap = ""
required_to_buy = "Infantry"
angle = "*/-/-/-"
orders_lost = [ "",]
special = ""
ap = "1"
name = "AT-rifle"
cost = "6cp to upgrade an all weapons in a infantry base"
type_ = "Infantry 2-handed weapon"
assault_special = ""
range_ = "5"
damage = "d6-1"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = "r"
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units."Elk Cavalry"]
assault_special = "Cunning Assault[1 for 3]"
size = "medium"
members = "2"
race = "Elf"
assault_deflection = "1/-/-/-"
assault_deflection_die = "5+"
armor = ""
assault = "4/4/2/2"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = ""
assault_pen = "-2"
type_ = "Bio, Cavalry"
weapons_input = [ "Grenade",]
assault_ap = ""
name = "Elk Cavalry"
cost = "2mp, 1xp"
assault_damage = "d6-2"

[units."Tatto INK"]
assault_special = ""
size = "Large"
members = "1"
race = "Elf"
assault_deflection = "2/-/-/-"
assault_deflection_die = "5+"
armor = "3/1/1/1"
assault = "3/2/2/2"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Gun Blazing: Ignore to-hit penalties when moving fast\\\\ May fire SMG in addition to Gattle Gun any time a fire order is given, and SMG is always treated as loaded\\\\ SMG must fire in same angle as Gattle Gun\\\\ Movement: road: if on a road, you may move along a road using this order"
assault_pen = "-1"
type_ = "Mechanical, Bio Crew, Half-track"
weapons_input = [ "Gattle Gun", "SMG",]
assault_ap = ""
name = "Tatto INK"
cost = "2ip"
assault_damage = "d6-1"

[weapons."Deflection Field"]
assault_ap = ""
required_to_buy = ""
angle = ""
orders_lost = [ "",]
special = ""
ap = ""
name = "Deflection Field"
cost = "4cp to upgarde 1 vehicle"
type_ = "Mechanical upgrade"
assault_special = ""
range_ = ""
damage = ""
race = "Elf"
assault_deflection_die_set_to = "5+"
assault_mod = "-"
assault_deflection_mod = "+6/+6/+6/+6"
orders_gained = [ "",]
template = "a"
pen = ""
assault_dam_set_to = "n.a"
assault_pen_set_to = "n.a"
filters = [ "team",]

[units."Elite Infantry"]
assault_special = "Cunning Assault[1 for 2]"
size = "medium"
members = ""
race = "Elf"
assault_deflection = "1/-/-/-"
assault_deflection_die = "5+"
armor = ""
assault = "2/1/1/1"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = "Unit gain good shot +1 and psychic resistance 1"
assault_pen = "-2"
type_ = "Bio, Infantry"
weapons_input = [ "Rifle",]
assault_ap = ""
name = "Elite Infantry"
cost = "1xp to upgrade up to 2 normal infantry units."
assault_damage = "d6-2"

[units."Bear Rider"]
assault_special = "Cunning Assault[1 for 3]"
size = "medium"
members = "1"
race = "Elf"
assault_deflection = "1/-/-/-"
assault_deflection_die = "5+"
armor = "2/1/1/1"
assault = "6/4/2/1"
filters = [ "weapons", "team",]
assault_die = "5+"
unit_special = ""
assault_pen = "-2"
type_ = "Bio, Cavalry"
weapons_input = [ "MiniGun",]
assault_ap = ""
name = "Bear Rider"
cost = "1mp, 4xp"
assault_damage = "d6+1"

[weapons."Main Tank Gun"]
assault_ap = ""
required_to_buy = ""
angle = "*/*/*/*"
orders_lost = [ "",]
special = "double barraled: may load up to 2 shots. But fire them one at a time"
ap = "3"
name = "Main Tank Gun"
cost = ""
type_ = "Tank gun"
assault_special = ""
range_ = "6"
damage = "d6+3 when penetrating all armor"
race = "Elf"
assault_deflection_die_set_to = ""
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
template = ""
pen = ""
assault_dam_set_to = ""
assault_pen_set_to = ""
filters = [ "team",]

[units."Eagle Rider".orders]
Movement = [ "(fly, fast) 360$^0$ + F + F", "(fly, fast) 360$^0$,F + F + F,360$^0$", "(fly, fast) chase + chase + chase", "(fly, fast) 360$^0$,F + F + Land", "(on ground, slow) 360$^0$ + F + 360$^0$", "(on ground, slow) 360$^0$ + 360$^0$ + 360$^0$", "(on ground, slow) 360$^0$ + TakeOff + F", "(Default, on-ground slow) TakeOff + Flee + 360$^0$ ", "(Default, fly, fast) Flee + Flee + Flee",]
"Fire Orders" = [ "- + Fire (AT-rifle)", "- + load (AT-rifle)", "- + Throw Grenade", "- + aim (AT-rifle) (on ground only)",]

[units.Infantry.damage_tables]
"Psychic damage" = [ "4+ shaken",]
"Regular damage" = [ "0-6: kill 1 member", "7-8: kill 1 member, psychic damage[d6]", "9: kill all 4",]

[units."VelociRaptor Riders".orders]
"Fire Actions" = [ "fire(smg) + fire(smg)", "load(5)(smg) + - ", "fire(twin-gun) + - (stand still only)", "load(twin-gun) + -", "- + load(twin gun)", "- + aim (twin gun)", "- + fire(twin gun) (stand still only)",]
Movement = [ "(fast) 360$^0$ + F + F", "(fast) F + B + 360$^0$", "(fast) F + F + 360$^0$", "(slow) 360$^0$ + A + F", "(slow) B + 360$^0$ + -", "(stand still) - + -  + -", "(stand still) A + F + -", "(stand still) 360$^0$ + - + -", "(stand still) A + A + F", "(fast) F + B + B,360$^0$", "(fast) F + F+ F", "(fast) F + F,360$^0$ + B,",]

[units."VelociRaptor Riders".damage_tables]
"Psychic damage" = [ "4+: shaken",]
"Regular Damage" = [ "2-3: Bleed[4]", "4+: kill 1, stop bleeding, pcysic damage[1d6]",]

[units."Elite Infantry".orders]
"" = [ "",]

[units."Elite VelociRaptor Riders".damage_tables]
"" = [ "",]

[units.Infantry.orders]
"Movement Orders" = [ "(slow) 360$^0$ + F + 360$^0$", "(slow) 360$^0$ + 360$^0$ + 360$^0$", "(slow) 360$^0$ + B + -", "(stand-still) 360$^0$ + - + -", "(stand-still) A + 360$^0$ + F", "- + - + -", "(slow) 360$^0$,A + F + F", "(fast) 360$^0$ + F + B[rest]", "(rest) - + - + A(slow)", "(rest) - + - + A(stand-still)", "(stand still) 360$^0$,A,A + F + F",]
"Fire Orders" = [ "(stand-still only) - + Fire", "(stand-still only) Fire + - ", "(stand-still only) - + load", "(stand-still only) load + -", "(stand-still only) - + aim", "(stand-still only) aim + - ",]

[units."Elite Infantry".damage_tables]

[units.E34.orders]
Fire = [ "- + Fire", "- + Aim (stand still and slow only)", "- + Load (stand still and slow only",]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + F + -", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow) F + - + -", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "(fast) R+ F + -", "(fast) L+ F + -", "(fast) road + road + road",]

[units.E34.damage_tables]
"Critical Damage" = [ "1: cannot move forward", "2: -1 to hit, +1 to be hit", "3: Rotates right in misc step 2", "4: rotates left in misc step 1 and 3", "5: Stuck turret: firing angle is now */-/-/-", "6: Unit is set on fire",]
"Regular Damage" = [ "1-4: Lightly Damaged", "4-8: Crittical Damage, +1 on future damage", "9+ Destoryed",]
"Lightly Damaged" = [ "1-3: shaken", "4-6: +1 on future damage",]

[units."Elk Cavalry".orders]
"Fire orders" = [ "- + Throw Grenade",]
Movement = [ "(slow) 360$^0$ + F + 360$^0$", "(slow) 360$^0$ + A + F", "(fast) F+F+B",]

[units."Tatto INK".orders]
Fire = [ "fire + aim (stand still only)", "aim + fire (stand still only)", "fire + fire ", "load + aim (stand still only)", "load + load (stand still and slow only)",]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + F + -", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow) F + - + -", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "(fast) R+ F + -", "(fast) L+ F + -", "(fast) road + road + road",]

[units."Sniper Tank".orders]
Fire = [ "- + Fire (all weapons)", "(stand-still) - + Aim", "(stand-still, slow) - + Load",]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + F + -", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow) F + - + -", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "(fast) R+ F + -", "(fast) L+ F + -",]

[units."Sniper Tank".damage_tables]
"Critical Damage" = [ "1: cannot move forward", "2: -1 to hit, +1 to be hit", "3: Rotates right in misc step 2", "4: rotates left in misc step 1 and 3", "5: Stuck turret: firing angle is now */-/-/-", "6: Unit is set on fire",]
"Regular Damage" = [ "1-4: Lightly Damaged", "4-8: Crittical Damage, +1 on future damage", "9+ Destoryed",]
"Lightly Damaged" = [ "1-3: shaken", "4-6: +1 on future damage",]

[units."Tatto INK".damage_tables]
"Heavily Damage" = [ "1: +1 on future damage", "2: -1 to hit, +1 to be hit", "3: cannot rotate right", "4: cannot rotate left", "5: Treat all B and A as illegal. Replace with -", "6: Fire!",]
"Lightly Damage" = [ "1-3: shaken", "4-6: +1 on future damage",]
"Regular Damage" = [ "1-3: Lightly Damaged", "4-6: Heavily Damaged, +1 on future damage", "7+ Destroyed",]

[units."Elk Cavalry".damage_tables]
"psychic damage" = [ "4+ shaken",]
"Regular damage" = [ "1-3: Bleed[4]", "4-8: kill 1 memeber, psychic damage[d6]", "9: kill unit base",]

[units."Elite VelociRaptor Riders".orders]
"" = [ "",]

[units."Bear Rider".damage_tables]
"Psychic damage" = [ "6+: shaken",]
"Regular damage" = [ "2: +1 to future damage", "3-6: +1 to future damage, Bleed[4]", "7-9: +2 to future damage, Bleed[6], psychic damage[d6]", "10: killed",]

[units."Eagle Rider".damage_tables]
"psychic damage" = [ "6+ shaken",]
"Regular Damage" = [ "2-3: bleeding[4], +1 to future damge", "4-5: bleeding[6], +2 to future damage, psychic damage[d6]", "6+: killed",]

[units."Bear Rider".orders]
"Fire orders" = [ "+ - load", "+ - fire", "+ - aim",]
Movement = [ "(slow) 360$^0$ + F + 360$^0$", "(default slow) - + Flee + 360$^0$",]
