name = "Ork"

[weapons."Clockwork Spear"]
pen = ""
orders_gained = [ "",]
name = "Clockwork Spear"
race = "Ork"
assault_dam_set_to = "d8"
assault_mod = "unmodified"
special = ""
damage = ""
assault_special = "Cunning[1 for 2]"
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "n.a"
assault_deflection_mod = "-"
required_to_buy = "Infantry base"
cost = "1cp to upgrade alle infantry in unit base"
ap = ""
template = "a"
angle = ""
type_ = "1 handed Infantry Weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = ""

[units.Grunt]
assault_special = "Any 6 on assult die roll (not assault deflection) count as two success and you get to reroll 3 dice (identical rules original die). (exploding die)"
assault_damage = "d6-2"
unit_special = "Cannot use ranged weapons"
race = "Ork"
assault_deflection_die = ""
members = "4"
assault_die = "6+"
cost = "1mp"
assault = "2/2/2/2"
assault_pen = "-2"
assault_deflection = ""
type_ = "Bio, Infantry"
armor = ""
assault_ap = ""
size = "medium"
name = "Grunt"
weapons_input = [ "",]
filters = [ "weapons", "team",]

[weapons."Ork Musket"]
pen = "-2"
orders_gained = [ "",]
name = "Ork Musket"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = ""
damage = "d6-1"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = ""
cost = ""
ap = ""
template = ""
angle = "*/*/-/-"
type_ = ""
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "3"

[units.HammerHead]
assault_special = "You may reroll up too 3 dice per 6 this unit roll in regular assaults. Assault deflection die may not be used to deflect attacks against you, but negate the enemies assault deflection dice instead"
assault_damage = "d8+3/d8/d8/d8"
unit_special = "Has 4 Harpoon Guns which are all fired within same angle-sector when firing"
race = "Ork"
assault_deflection_die = "6+"
members = "1"
assault_die = "6+"
cost = "4ip"
assault = "12/8/8/8"
assault_pen = ""
assault_deflection = "12/2/2/2"
type_ = "Mechanical, Bio, Crew, Tracked"
armor = "8/5/2/2"
assault_ap = "5/-2/-2/-2"
size = "Large"
name = "HammerHead"
weapons_input = [ "Harpoon Gun",]
filters = [ "weapons", "team",]

[units.Warhero]
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice (identical rules to the original die) (exploding die)"
assault_damage = "d6"
unit_special = "Not jet dead: after all 4 infantry in the unit base are killed, there is one that is not dead jet afterall. Becomes an awakened war hero."
race = "Ork"
assault_deflection_die = "6+"
members = ""
assault_die = "6+"
cost = "3xp to upgrade up to either 2 grunts or 2 regular infantry"
assault = "3/2/2/2"
assault_pen = "-2"
assault_deflection = "1/-/-/-"
type_ = "Bio, Infantry"
armor = ""
assault_ap = ""
size = "medium"
name = "Warhero"
weapons_input = [ "",]
filters = [ "weapons", "team",]

[weapons.Pyro]
pen = "special"
orders_gained = [ "(stand-still, slow) - + Throw",]
name = "Pyro"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "Choose one hex within range, and each memember tries to throw one grenade at an enemy in that hex. If enemy base is hit atleast once, that enemy is set on fire. \\\\ Don't need to be loaded to be used.\\\\ Bonus weapon, can be added to any other combination of weapons.\\\\ "
damage = "special"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = "Infantry"
cost = "1cp, 1xp to give all units in unit base Pyro"
ap = ""
template = "r"
angle = "*/*/*/*"
type_ = "Misc Infantry Weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "1"

[weapons."Grenade Sling"]
pen = ""
orders_gained = [ "",]
name = "Grenade Sling"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "Choose one hex within normal range, area(6+) \\\\ AP not reduced by distance\\\\ If combined with the pyro, the pyro gains standar range of 3 instead of 1"
damage = "d6"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = ""
cost = "3cp to give all units in unit base Grenade Sling"
ap = "1"
template = "r"
angle = "*/*/*/*"
type_ = "1 handed infantry weapon."
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "3"

[units.Troll]
assault_special = "Reduce damage by 2 for each successfull assault deflection rolled by enemy"
assault_damage = "d6+12"
unit_special = "May have a maxium of twelve -1 counters to assault damage, and 1 momentarily killed token\\\\ At each aftermath face, remove/downgrade up to three of the following: one +1 for future damage marker, downgrade one bleeding one step, one -1 counter to assault damage or 1 momentarily killed token.\\\\"
race = "Ork"
assault_deflection_die = ""
members = "1"
assault_die = "5+"
cost = "8xp"
assault = "10/8/6/4"
assault_pen = ""
assault_deflection = ""
type_ = "Bio, Monster"
armor = ""
assault_ap = ""
size = "Huge"
name = "Troll"
weapons_input = [ "",]
filters = [ "weapons", "team",]

[weapons.Flamecoveredaxe]
pen = ""
orders_gained = [ "",]
name = "Flamecoveredaxe"
race = "Ork"
assault_dam_set_to = "d6+1"
assault_mod = "unmodified"
special = ""
damage = ""
assault_special = "Fire"
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "n.a"
assault_deflection_mod = "-"
required_to_buy = ""
cost = "2cp to upgrade weapons of single Warhero"
ap = ""
template = "a"
angle = ""
type_ = "1 handed elite infantry weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = ""

[weapons."Ork Pistol"]
pen = "-2"
orders_gained = [ "(stand-still) load(2) + -", "(stand-still) - + load(2)", "(stand-still, slow) fire + -", "(stand-still, slow) - + fire",]
name = "Ork Pistol"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "1 handed weapon. Infantry may combine pistol with another 1-handed weapon."
damage = "d6-1"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = "Infantry"
cost = "1cp to upgrade  all weapons of up to 2 regular ork infantry base"
ap = ""
template = "r"
angle = "*/*/*/*"
type_ = "1 handed infantry weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "3"

[units."Awakened war hero"]
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 6 dice (with identical rules to this one) (exploding die)"
assault_damage = "d6"
unit_special = "has same orders available as the unit base it awakened from, and the same weapons as the last surviving member of the unit base"
race = "Ork"
assault_deflection_die = "6+"
members = "1"
assault_die = "6+"
cost = ""
assault = "6/3/3/3"
assault_pen = ""
assault_deflection = "2/-/-/-"
type_ = "Bio, Infantry"
armor = ""
assault_ap = ""
size = "medium"
name = "Awakened war hero"
weapons_input = [ "",]
filters = [ "weapons", "team",]

[weapons."Hand Held Cannon"]
pen = "0"
orders_gained = [ "",]
name = "Hand Held Cannon"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "Unit base gets the option to fire this weapon instead of regular weapons. "
damage = "+3 damage if penetrating armor"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = ""
cost = "4cp to give this weapon to 1 unit base"
ap = "4"
template = "r"
angle = "*/-/-/-"
type_ = "Infantry base weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "4"

[weapons."Pistol with Spear"]
pen = "-2"
orders_gained = [ "Load(2)",]
name = "Pistol with Spear"
race = "Ork"
assault_dam_set_to = "d8"
assault_mod = "unmodified"
special = "1 handed weapon. Pistol with a clockwork Spear."
damage = "d6-1"
assault_special = "Cunning[1 for 2]"
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "unmodified"
assault_deflection_mod = "-"
required_to_buy = "Warhero or Warg Rider"
cost = "1cp to upgrade a single warhero infantry"
ap = ""
template = "ra"
angle = "*/*/*/*"
type_ = "Elite Infantry Weapon"
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "3"

[weapons."Clockwork Wings"]
pen = ""
orders_gained = [ "(slow) A + Chase + Chase", "(fast) Chase + Chase + B",]
name = "Clockwork Wings"
race = "Ork"
assault_dam_set_to = "unmodified"
assault_mod = "+1/-/-/-"
special = "Does not fly, but those wings really help jumping and running."
damage = ""
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "-"
assault_deflection_mod = "unmodified"
required_to_buy = "Infantry base"
cost = "3cp to upgrade one infantry base"
ap = ""
template = "a"
angle = ""
type_ = "Infantry Misc. May be added independent off other equipment."
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = ""

[weapons.MG]
pen = "-2"
orders_gained = [ "(stand still) B[Setup] + - + -", "(setup): - + - + A[stand-still]", "(setup): load MG + - ", "(setup): fire + -",]
name = "MG"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "Fire at ALL units (friend or foe) within fireing angle and range.\\\\ Unit base gains Take Cover[setup][-2]"
damage = "d6-2"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = ""
cost = "6cp to give MG to one infantry base"
ap = ""
template = "r"
angle = "*/-/-/-"
type_ = "Infantry base weapon."
assault_pen_set_to = ""
orders_lost = [ "(stand-still) load", "(stand-still) fire",]
range_ = "5"

[weapons."Harpoon Gun"]
pen = "-2"
orders_gained = [ "",]
name = "Harpoon Gun"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "If one single-member unit of size large or smaller is hit by this weapon but not killed, move the target one hex towards you in agony 0. Keep the orientation of the unit. If there are multiple hexes which you can move the target to move it towards you, you may choose where to move the enemy. If this movement forces the target to move into a hex occupied by you, carry out an assault. If this movement turns the hex into an overcrowed hex, do not move this unit but turn in into a shaken unit instead"
damage = "d6-2"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = "Regular Infantry Base"
cost = "2cp to give one infantry base this weapon"
ap = ""
template = "r"
angle = "*/*/*/*"
type_ = "Infantry Base weapon, or vehicle/tank weapon."
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "5"

[weapons."Clockwork Shield"]
pen = ""
orders_gained = [ "",]
name = "Clockwork Shield"
race = "Ork"
assault_dam_set_to = "unmodified"
assault_mod = "unmodified"
special = "Unit base gains damage resistance 1 \\\\ Weapon uses 1 hand"
damage = ""
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "6+"
assault_deflection_mod = "+1/-/-/-"
required_to_buy = "Infantry base"
cost = "1cp to give all units in one grunt or regular base sheilds"
ap = ""
template = "a"
angle = ""
type_ = "1 handed infantry weapon"
assault_pen_set_to = "unmodified"
orders_lost = [ "",]
range_ = ""

[weapons."Heavy MG"]
pen = "-1"
orders_gained = [ "",]
name = "Heavy MG"
race = "Ork"
assault_dam_set_to = ""
assault_mod = ""
special = "Area(6+) or with aim, fire 6 times at same enemy unit base."
damage = "d6-1"
assault_special = ""
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = ""
assault_deflection_mod = ""
required_to_buy = ""
cost = ""
ap = ""
template = ""
angle = "*/-/-/-"
type_ = ""
assault_pen_set_to = ""
orders_lost = [ "",]
range_ = "3"

[units.Halftrack]
assault_special = "May unload 1 infantry or grunt as part of assault"
assault_damage = "d6-1"
unit_special = "Bad Shot (-1 to hit) \\\\ May transport up to 2 grunts or 1 infantry. "
race = "Ork"
assault_deflection_die = "6+"
members = "1"
assault_die = "6+"
cost = "2ip"
assault = "4/3/2/1"
assault_pen = ""
assault_deflection = "2/-/-/-"
type_ = "Mechanical"
armor = "2/1/1/1"
assault_ap = ""
size = "large"
name = "Halftrack"
weapons_input = [ "Heavy MG",]
filters = [ "weapons", "team",]

[weapons."Clockwork Power Spear"]
pen = ""
orders_gained = [ "",]
name = "Clockwork Power Spear"
race = "Ork"
assault_dam_set_to = "d12"
assault_mod = "unmodified"
special = ""
damage = ""
assault_special = "Cunning[1 for 2]."
assault_ap = ""
filters = [ "team",]
assault_deflection_die_set_to = "n.a"
assault_deflection_mod = "-"
required_to_buy = "Infantry"
cost = "2cp to give all infantry in one unit base the Power Spear"
ap = ""
template = "a"
angle = ""
type_ = "2-handed Infantry Weapon"
assault_pen_set_to = "-1"
orders_lost = [ "",]
range_ = ""

[units."Warg Rider"]
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice (identical rules to the original die) (exploding die)"
assault_damage = "d6-2"
unit_special = "May use crafts (both melee and ranges) which uses 1 hand. Fire orders only available if given ranged weapon"
race = "Ork"
assault_deflection_die = "6+"
members = "2"
assault_die = "6+"
cost = "1mp, 2xp"
assault = "4/4/4/4"
assault_pen = ""
assault_deflection = "2/2/1/1"
type_ = "Bio, Cavalery, Walks"
armor = ""
assault_ap = ""
size = "medium"
name = "Warg Rider"
weapons_input = [ "",]
filters = [ "weapons", "team",]

[units.Infantry]
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice (identical rules to the original die) (exploding die)"
assault_damage = "d6-2"
unit_special = "Bad shot: -1 to hit with ranged weapons. \\\\ Take Cover[stand-still][-2]"
race = "Ork"
assault_deflection_die = ""
members = "4"
assault_die = "6+"
cost = "2mp"
assault = "2/2/2/2"
assault_pen = "-2"
assault_deflection = ""
type_ = "Bio, Infantry"
armor = ""
assault_ap = ""
size = "medium"
name = "Infantry"
weapons_input = [ "Ork Musket",]
filters = [ "weapons", "team",]

[units.Warhero.orders]
"" = [ "",]

[units."Warg Rider".damage_tables]
"Psychic Damage" = [ "5+: unit shaken",]
"Regular Damage" = [ "2-3: Bleeding[6]", "4-5: Bleeding[6], +1 to future damage, psychic damage[d6]", "6+: kill 1 member, pscic damage[d6]",]

[units.Halftrack.damage_tables]
"Critical damage" = [ "1-2: Unit cannot accelerate any more. ", "3-4: unit cannot break any more", "5-6: unit gains +1 to be hit and -1 to hit.",]
"Lightly damage" = [ "1-2: +1 on future damage", "3-4: Unit shaken", "5-6: Roll a d6 of regular damage to each transported unit base.",]
"Regular Damage" = [ "1-4: roll on lightly damage [d6]", "5-8: +1 on future damage, roll for critical damage[d6]", "9+: Unit destroied",]

[units."Awakened war hero".damage_tables]
"Regular Damage" = [ "2-3: Bleeding[4]", "4+ : Killed",]

[units.Troll.damage_tables]
"Regular Damage" = [ "1-3: +1 for future damage", "4-6: +1 for future damage, bleed[4]", "7-8: +2 for future damage, bleed[4]", "10-12: +2 for future damage, bleed[6]", "13-15: +3 for future damage, bleed[6]", "16-18: +3 for future damage, bleed[8]", "19-21: +4 for future damage, bleed[8]", "22-24: +4 for future damage, bleed[10], -1 (cumulative) on assault damage", "25-27: +5 for future damage, bleed[12], -2 (cumulative) on assault damage", "28-29: +10 for future damage, bleed[12], -4 (cumulative) on assault damage", "30-99: as 28-29 pluss Troll Momentarily killed", "100+: Troll permanently killed",]

[units.Infantry.orders]
"Movement Orders" = [ "(slow) 360$^0$ + F + 360$^0$", "(slow) 360$^0$ + 360$^0$ + 360$^0$", "(slow) 360$^0$ + B + -", "(stand-still) 360$^0$ + - + -", "(stand-still) 360$^0$ + A + F", "(slow) - + - + chase",]
"Fire Orders" = [ "(stand-still) - + Fire", "(stand-still) Fire + - ", "(stand-still) - + load", "(stand-still) load + -", "(stand-still) - + aim", "(stand-still) aim + - ",]

[units.HammerHead.orders]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + B + B", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "(slow) R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow)  - + B + B", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "(stand-still) aim + - + -",]
Fire = [ "(stand still) load + -", "(stand still) load unstable + -", "(stand still) aim + -", "(all) fire + -",]

[units.HammerHead.damage_tables]
"Critical damage" = [ "1-3: roll on lightly damage 3 times", "4: Unit cannot rotate Left", "5: Unit Cannot rotate Right", "6: Harpoon guns destroied.",]
"Lightly Damage" = [ "1-3: unit shaken", "4-5: +1 on all future damage", "6: -2/-2/-2/-2 (cumulative) on assault values",]
"Regular Damage" = [ "1-5: Lightly damage[d6]", "6-8: Crittical Damage, +1 on all future damage", "9+: unit desestroyed",]

[units.Halftrack.orders]
Fire = [ "Fire (heavy MG) + -", "- + Fire (heavy MG)", "Load(2) + -", "(stand-still or slow) aim + -", "(stand-still or slow) - + aim", "- + Load(2)",]
"Movement orders" = [ "(fast): F + F + F", "(fast): F + F + R", "(fast): F + F + L", "(fast): F + F + Unload", "(stand-still): R + - + -", "(stand-still): L + - + -", "(stand-still): R + R + -", "(stand-still): R + R + R", "(stand-still): L + L + L", "(stand-still) L + L + -", "(stand-still): rev + - + -", "(stand-still): Unload + - + -", "(slow): A + F + R", "A + F + L", "(slow): A + F + -", "(slow): B + - + -", "(slow): B + rev + -", "(slow): L + L + -", "(slow): L + - + -", "(slow): R + R + -", "(slow): R + - + - ", "(slow): F + R + Unload", "(slow): F + L + Unload", "(slow): F + Unload + -",]

[units.Warhero.damage_tables]
"" = [ "",]

[units.Grunt.orders]

[units."Warg Rider".orders]
"Fire Orders" = [ "load + -", "fire + -", "- + fire",]
"Movement orders" = [ "Fast: 360$^0$ + F + F", "Fast: F + 360$^0$ + F", "Fast: F + F + 360$^0$", "Fast: F + B + 360$^0$", "Slow: 360$^0$ + 360$^0$ + 360$^0$", "Slow: 360$^0$ + A + F",]

[units."Awakened war hero".orders]
"" = [ "",]

[units.Grunt.damage_tables]
"Psychic damage" = [ "4+: unit base shaken",]
"Regular damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psychic damage[d6]", "9+: destroy unit base",]

[units.Troll.orders]
"Main orders" = [ "- + - + Chase",]

[units.Infantry.damage_tables]
"Psychic Damage" = [ "4+: unit base shaken",]
"Regular Damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psychic damage [d6]", "9+ Destroy Unit Base",]
