name = "Ork"
orders = ""

[weapons."Mechanical Shield"]
range_ = ""
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = ""
angle = ""
filters = [ "team",]
assault_ap = ""
pen = ""
race = "Ork"
requiered_to_buy = "Grunts, Infantry"
assault_special = ""
name = "Mechanical Shield"
assault_mod = ""
assault_deflection_mod = "+1/-/-/-"
orders_gained = [ "",]
special = "Units gains damage resistance 1 \\ Weapon uses 1 hand"
cost = "1cp"
type_ = ""
damage = ""
assault_deflection_die_set_to = "6+"

[weapons."Hand Held Cannon"]
range_ = "4"
assault_dam_set_to = ""
orders_lost = [ "",]
ap = "4"
assault_pen_set_to = ""
angle = "*/-/-/-"
filters = [ "team",]
assault_ap = ""
pen = "0"
race = "Ork"
requiered_to_buy = "Infantry"
assault_special = ""
name = "Hand Held Cannon"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
special = "Unit base gets the option to fire this weapon instead of regular weapons. "
cost = "4cp"
type_ = "Infantry base weapon"
damage = "+3 damage if penetrating armor"
assault_deflection_die_set_to = ""

[weapons."Ork Musket"]
range_ = "3"
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = ""
angle = "*/*/-/-"
filters = [ "team",]
assault_ap = ""
pen = "-2"
race = "Ork"
requiered_to_buy = ""
assault_special = ""
name = "Ork Musket"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
special = ""
cost = ""
type_ = ""
damage = "0"
assault_deflection_die_set_to = ""

[weapons."Heavy MG"]
range_ = "3"
assault_dam_set_to = ""
orders_lost = [ "",]
ap = "0"
assault_pen_set_to = ""
angle = "*/-/-/-"
filters = [ "team",]
assault_ap = ""
pen = "-1"
race = "Ork"
requiered_to_buy = ""
assault_special = ""
name = "Heavy MG"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
special = "Area(6+) or with aim, fire 6 times at same enemy unit base."
cost = ""
type_ = ""
damage = "-1"
assault_deflection_die_set_to = ""

[weapons."Mechanical Spear"]
range_ = ""
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = "-2"
angle = ""
filters = [ "team",]
assault_ap = ""
pen = ""
race = "Ork"
requiered_to_buy = "Grunts, Infantry, Warg Cavalry"
assault_special = "Roll a d8 instead of a d6 for regular damage after assault\\ Fear(4)"
name = "Mechanical Spear"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
special = "Units gains damage resistance 1 \\ Weapon uses 1 hand"
cost = "1cp"
type_ = ""
damage = ""
assault_deflection_die_set_to = ""

[weapons.Pyro]
range_ = "1"
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = ""
angle = "*/*/*/*"
filters = [ "team",]
assault_ap = ""
pen = "special"
race = "Ork"
requiered_to_buy = "Infantry, Warg Rider"
assault_special = ""
name = "Pyro"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "360^0+F + -  + Throw ",]
special = "Choose one hex within range, and each memember tries to throw one grenade at an enemy in that hex. If enemy base is hit atleast once, that enemy is set on fire. \\ Don't need to be loaded to be used.\\ Bonus weapon, can be added to any other combination of weapons.\\ "
cost = "1cp, 1xp"
type_ = ""
damage = "special"
assault_deflection_die_set_to = ""

[units.Halftrack]
name = "Halftrack"
size = "large"
assault_deflection_die = "6+"
assault_special = ""
assault_die = "6+"
assualt_damage = "-1"
armor = "2/1/1/1"
filters = [ "weapons", "team",]
cost = "2ip"
members = "1"
assault = "4/3/2/1"
assault_deflection = "1/-/-/-"
type_ = "Mechanical"
assualt_pen = "-1"
race = "Ork"
unit_special = "Bad Shot (-1 to hit) \\ Fires after movement\\ May transport up to 2 grunts or 1 infantry. "
weapons_input = [ "Heavy MG",]

[weapons."Steam MG"]
range_ = "5"
assault_dam_set_to = ""
orders_lost = [ "(slow) load", "(slow) fire",]
ap = "0"
assault_pen_set_to = ""
angle = "*/-/-/-"
filters = [ "team",]
assault_ap = ""
pen = "-2"
race = "Ork"
requiered_to_buy = "Infantry"
assault_special = ""
name = "Steam MG"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "(slow) Setup", "(setup): Pick up equipment", "(setup): load", "(setup): fire",]
special = "Fire at ALL units (friend or foe) within fireing angle and range. In addition, unit gain an entrenchemnt while setup."
cost = "6cp"
type_ = ""
damage = "-2"
assault_deflection_die_set_to = ""

[weapons."Mechanical Wings"]
range_ = ""
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = ""
angle = ""
filters = [ "team",]
assault_ap = ""
pen = ""
race = "Ork"
requiered_to_buy = "Infantry, Grunt"
assault_special = ""
name = "Mechanical Wings"
assault_mod = "+1/-/-/-"
assault_deflection_mod = ""
orders_gained = [ "[movement] Chase + Chase + Chase",]
special = "Does not fly, but those wings really help jumping and running."
cost = "3cp to upgrade one infantry base"
type_ = "Infantry Misc. May be added independent off other equipment."
damage = ""
assault_deflection_die_set_to = ""

[units.Infantry]
name = "Infantry"
size = "medium"
assault_deflection_die = ""
assault_special = "Any 6 rolled in assault count as two.\\ In addition, you may reroll 1 die (assault or assault deflection) if you roll a 6 in assault. Repeat if you get more 6's"
assault_die = "6+"
assualt_damage = "-1"
armor = ""
filters = [ "weapons", "team",]
cost = "2mp"
members = "4"
assault = "2/2/2/2"
assault_deflection = ""
type_ = "Bio, Infantry"
assualt_pen = "-2"
race = "Ork"
unit_special = "Bad shot: -1 to hit with ranged weapons. \\ May choose to fire before or after movement."
weapons_input = [ "Ork Musket",]

[weapons."Power Spear"]
range_ = ""
assault_dam_set_to = ""
orders_lost = [ "n",]
ap = ""
assault_pen_set_to = "-1"
angle = ""
filters = [ "team",]
assault_ap = ""
pen = ""
race = "Ork"
requiered_to_buy = "Grunts, Infantry or Warg Rider"
assault_special = "When rolling regular damage, roll a d12 instead of a d6. \\ fear(6)"
name = "Mechanical Power Spear"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "",]
special = ""
cost = "2cp"
type_ = ""
damage = ""
assault_deflection_die_set_to = ""

[units.grunt]
name = "grunt"
size = "medium"
assault_deflection_die = ""
assault_special = "Any 6 on assult die roll (not assault deflection) count as two success and you get to reroll 2 dice (identical rules to this die). (exploding die)"
assault_die = "6+"
assualt_damage = "-1"
armor = ""
filters = [ "weapons", "team",]
cost = "1mp"
members = "4"
assault = "2/2/2/2"
assault_deflection = ""
type_ = "Bio, Infantry"
assualt_pen = "-2"
race = "Ork"
unit_special = "Cannot use ranged weapons"
weapons_input = [ "",]

[units.Troll]
name = "Troll"
size = "Huge"
assault_deflection_die = ""
assault_special = "Reduce damage by 2 for each successfull assault deflection rolled by enemy"
assault_die = "5+"
assualt_damage = "+12"
armor = ""
filters = [ "weapons", "team",]
cost = "8xp"
members = "1"
assault = "10/8/6/4"
assault_deflection = ""
type_ = ""
assualt_pen = "-2"
race = "Ork"
unit_special = "May have a maxium of twelve -1 counters to assault damage, and 1 momentarily killed token\\ At each aftermath face, remove/downgrade up to three of the following: one +1 for future damage marker, downgrade one bleeding one step, one -1 counter to assault damage or 1 momentarily killed token.\\"
weapons_input = [ "",]

[units."Warg Rider"]
name = "Warg Rider"
size = "medium"
assault_deflection_die = ""
assault_special = "Any 6 in assault counts as 2 success. \\ In addition, reroll any 3 dice (assault or assault deflection by you) for each 6 you roll for assault. Repeat if you get another 6"
assault_die = "6+"
assualt_damage = "0"
armor = ""
filters = [ "weapons", "team",]
cost = "1mp, 2xp"
members = "2"
assault = "4/4/4/4"
assault_deflection = "2/2/1/1"
type_ = ""
assualt_pen = "-2"
race = "Ork"
unit_special = "May use crafts (both melee and ranges) which uses 1 hand. Fire orders only available if given ranged weapon"
weapons_input = [ "",]

[weapons."Ork Pistol"]
range_ = "3"
assault_dam_set_to = ""
orders_lost = [ "",]
ap = ""
assault_pen_set_to = ""
angle = "*/*/*/*"
filters = [ "team",]
assault_ap = ""
pen = "-2"
race = "Ork"
requiered_to_buy = "Infantry, Warg Rider"
assault_special = ""
name = "Ork Pistol"
assault_mod = ""
assault_deflection_mod = ""
orders_gained = [ "load(2)",]
special = "1 handed weapon. Infantry may combine pistol with another 1-handed weapon."
cost = "1cp"
type_ = ""
damage = "-1"
assault_deflection_die_set_to = ""

[units.grunt.orders]
Movement = [ "- + - + Chase",]

[units.Troll.orders]
"Main orders" = [ "- + - + Chase",]

[units.Halftrack.orders]
"Movement orders" = ["Fast: F + F + F", "Fast: F + F + R", "Fast: F + F + L", "Fast: F + F + Unload", "Stand Still: R + - + -", "Stand Still: L + - + -", "Stand Still: R + R + -", "Stand Still: R + R + R", "Stand Still: L + L + L", "Stand Still L + L + -", "Stand Still: rev + - + -", "Stand Still: Unload + - + -", "Slow: A + F + R", "A + F + L", "Slow: A + F + -", "Slow: B + - + -", "Slow: B + rev + -", "Slow: L + L + -", "Slow: L + - + -", "Slow: R + R + -", "Slow: R + - + - ", "Slow: F + R + Unload", "Slow: F + L + Unload", "Slow: F + Unload + -"]
Fire = [ "Fire (heavy MG) + -", "- + Fire (heavy MG)", "Load(2) + -", "(stand-still or slow) aim + -", "(stand-still or slow) - + aim", "- + Load(2)",]

[units.Halftrack.damage_tables]
"Lightly damage" = [ "1-2: +1 on future damage", "3-4: Unit pinned", "5-6: Roll a d6 of regular damage to each transported unit base.",]
"Regular Damage" = [ "1-4: roll on lightly damage [d6]", "5-8: +1 on future damage, roll for critical damage[d6]", "9+: Unit destroied",]
"Critical damage" = [ "1-2: Unit cannot accelerate any more. ", "3-4: unit cannot break any_more", "5-6: unit gains +1 to be hit and -1 to hit.",]

[units."Warg Rider".orders]
"Movement orders" = [ "Fast: 360^o + F + F", "Fast: F + 360^0 + F", "Fast: F + F + 360^0", "Fast: F + B + 360^0", "Slow: 360^o + 360^0 + 360^0", "Slow: 360^0 + A + F",]
"Fire Orders" = [ "load", "fire",]

[units.Infantry.orders]
"Main orders" = ["360^0 + F + 360^0", "Fire + -", "Aim + -", "load + -"]

[units.Troll.damage_tables]
"Regular Damage" = [ "1-3: +1 for future damage", "4-6: +1 for future damage, bleed[4]", "7-8: +2 for future damage, bleed[4]", "10-12: +2 for future damage, bleed[6]", "13-15: +3 for future damage, bleed[6]", "16-18: +3 for future damage, bleed[8]", "19-21: +4 for future damage, bleed[8]", "22-24: +4 for future damage, bleed[10], -1 (cumulative) on assault damage", "25-27: +5 for future damage, bleed[12], -2 (cumulative) on assault damage", "28-29: +10 for future damage, bleed[12], -4 (cumulative) on assault damage", "30-99: as 28-29 pluss Troll Momentarily killed", "100+: Troll permanently killed",]

[units."Warg Rider".damage_tables]
"Psycic damage" = [ "5+: pin unit base",]
"Regular damage" = [ "2-5: kill 1 member", "6-8: kill 1 member, roll on psycic damage d[6]", "9+ Destroy unit base",]

[units.Infantry.damage_tables]
"Psycic Damage" = [ "4+: unit base pinned",]
"Regular Damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psycic damage [d6]", "9+ Destroy Unit Base",]

[units.grunt.damage_tables]
"Psycic damage" = [ "4+: unit base pinned",]
"Regular damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psycic damage[d6]", "9+: destroy unit base",]


