name = "Ork"

[weapons.Flame-covered-axe]
race = "Ork"
name = "Flame-covered-axe"
template = "a"
range_ = ""
angle = ""
special = ""
damage = ""
ap = ""
assault_mod = "unmodified"
assault_deflection_mod = "-"
assault_deflection_die_set_to = "n.a"
assault_dam_set_to = "d6+1"
assault_special = "Fire"
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "4cp"
required_to_buy = "Model: Elite Infantry"
type_ = "Infantry, 1handed weapon"
filters = [ "team",]

[weapons."Clockwork Shield"]
race = "Ork"
name = "Clockwork Shield"
template = "a"
range_ = ""
angle = ""
special = "Unit base gains damage resistance 1"
damage = ""
ap = ""
assault_mod = "unmodified"
assault_deflection_mod = "+1/-/-/-"
assault_deflection_die_set_to = "6+"
assault_dam_set_to = "unmodified"
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "2cp"
required_to_buy = "Unit Base: Infantry or Grunt"
type_ = "Infantry, 1handed weapon"
filters = [ "team",]

[weapons."Clockwork Spear"]
race = "Ork"
name = "Clockwork Spear"
template = "a"
range_ = ""
angle = ""
special = ""
damage = ""
ap = ""
assault_mod = "unmodified"
assault_deflection_mod = "-"
assault_deflection_die_set_to = "-"
assault_dam_set_to = "d8"
assault_special = "Cunning[1 for 2]"
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "2cp"
required_to_buy = "Unit Base: Infantry or Grunt"
type_ = "Infantry, 1handed Weapon"
filters = [ "team",]

[weapons."Clockwork Power Spear"]
race = "Ork"
name = "Clockwork Power Spear"
template = "a"
range_ = ""
angle = ""
special = ""
damage = ""
ap = ""
assault_mod = "unmodified"
assault_deflection_mod = "-"
assault_deflection_die_set_to = "n.a"
assault_dam_set_to = "d12"
assault_special = "Cunning[1 for 2]."
assault_ap = "-1"
orders_gained = [ "",]
orders_lost = [ "",]
cost = "4cp"
required_to_buy = "Unit Base: Infantry or Grunt"
type_ = "Infantry, 2handed Weapon"
filters = [ "team",]

[weapons."Heavy MG"]
race = "Ork"
name = "Heavy MG"
template = ""
range_ = "3"
angle = "*/-/-/-"
special = "Area(6+) or with aim, fire 6 times at same enemy unit base."
damage = "d6-1"
ap = "-1"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = ""
required_to_buy = ""
type_ = ""
filters = [ "team",]

[weapons."Ork Pistol"]
race = "Ork"
name = "Ork Pistol"
template = "r"
range_ = "3"
angle = "*/*/*/*"
special = "1 handed weapon. Infantry may combine pistol with another 1-handed weapon. \\\\ If combined with another pistol, you may load and fire both pistol simultaniously, but with an extra -1 to hit penalty."
damage = "d6-1"
ap = "-2"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "(stand-still) load(2) + -", "(stand-still) - + load(2)", "(stand-still, slow) fire + -", "(stand-still, slow) - + fire",]
orders_lost = [ "",]
cost = "1cp"
required_to_buy = "Unit Base: Infantry"
type_ = "Infantry, 1handed weapon"
filters = [ "team",]

[weapons."Clockwork Wings"]
race = "Ork"
name = "Clockwork Wings"
template = "a"
range_ = ""
angle = ""
special = "Flies for a short period of time."
damage = ""
ap = ""
assault_mod = "+1/-/-/-"
assault_deflection_mod = "unmodified"
assault_deflection_die_set_to = "-"
assault_dam_set_to = "unmodified"
assault_special = ""
assault_ap = ""
orders_gained = [ "(slow) A(fast, flying) + Chase + Chase", "(fast, flying) Chase + Chase + B(slow, land)",]
orders_lost = [ "",]
cost = "4cp"
required_to_buy = "Unit Base: Infantry or Grunt"
type_ = "Infantry, Independent Equipment"
filters = [ "team",]

[weapons.Pyro]
race = "Ork"
name = "Pyro"
template = "r"
range_ = "1"
angle = "*/*/*/*"
special = "Choose one hex within range, and each memember tries to throw one grenade at an enemy in that hex. If enemy base is hit atleast once, that enemy is set on fire. \\\\ Don't need to be loaded to be used.\\\\ Bonus weapon, can be added to any other combination of weapons.\\\\ "
damage = "special"
ap = "N.A."
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "(stand-still, slow) - + Throw",]
orders_lost = [ "",]
cost = "4cp, 4xp"
required_to_buy = "Unit Base: Infantry"
type_ = "Infantry, Independent Equipment"
filters = [ "team",]

[weapons.MG]
race = "Ork"
name = "MG"
template = "r"
range_ = "5"
angle = "*/-/-/-"
special = "Fire at ALL units (friend or foe) within fireing angle and range.\\\\ Unit base gains Take Cover[setup][-2] (see general rules)"
damage = "d6-2"
ap = "-2"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "(stand still) B[Setup] + - + -", "(setup): - + - + A[stand-still]", "(setup): load MG + - ", "(setup): fire + -",]
orders_lost = [ "(stand-still) load", "(stand-still) fire",]
cost = "12cp"
required_to_buy = "Unit Base: Infantry"
type_ = "Infantry, Unit base weapon."
filters = [ "team",]

[weapons."Hand Held Cannon"]
race = "Ork"
name = "Hand Held Cannon"
template = "r"
range_ = "4"
angle = "*/-/-/-"
special = "Unit base gets the option to fire this weapon instead of regular weapons. "
damage = "+3 damage if penetrating armor"
ap = "4"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "8cp"
required_to_buy = ""
type_ = "Infantry, Unit base weapon"
filters = [ "team",]

[weapons."War Drum"]
race = "Ork"
name = "War Drum"
template = "a"
range_ = ""
angle = ""
special = "Allows any unit with 'chase' orders to follow this unit instead of chasing the enemy. If you choose to follow, move one hex towards any unit with war drums instead of the closest enemy unit. The choise can be made after orders are revealed."
damage = ""
ap = ""
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "2xp"
required_to_buy = "Model: Infantry"
type_ = "Misc infantry equipment"
filters = [ "team",]

[weapons."Harpoon Gun"]
race = "Ork"
name = "Harpoon Gun"
template = "r"
range_ = "5"
angle = "*/*/*/*"
special = "If one single-member unit of size large or smaller is hit by this weapon but not killed, move the target one hex towards you in agony 0. Keep the orientation of the unit. If there are multiple hexes which you can move the target to move it towards you, you may choose where to move the enemy. If this movement forces the target to move into a hex occupied by you, carry out an assault. If this movement turns the hex into an overcrowded hex, or an impassable hex, do not move target unit but turn it into a shaken unit instead. If the enemy is flying, move the target to the ground"
damage = "d6-2"
ap = "-2"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "4cp"
required_to_buy = "Unit Base: Infantry"
type_ = "Infantry vehicle/tank weapon: Unit Base Weapon"
filters = [ "team",]

[weapons."Grenade Sling"]
race = "Ork"
name = "Grenade Sling"
template = "r"
range_ = "3"
angle = "*/*/*/*"
special = "Choose one hex within normal range, area(6+) \\\\ AP not reduced by distance\\\\ If combined with the pyro, the pyro gains standard range of 3 instead of 1"
damage = "d6"
ap = "1"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = "6cp"
required_to_buy = "Unit Base: Infantry"
type_ = "Infantry, 1handed weapon."
filters = [ "team",]

[weapons."Pistol with Spear"]
race = "Ork"
name = "Pistol with Spear"
template = "ra"
range_ = "3"
angle = "*/*/*/*"
special = "1 handed weapon. Pistol with a clockwork Spear."
damage = "d6-1"
ap = "-2"
assault_mod = "unmodified"
assault_deflection_mod = "-"
assault_deflection_die_set_to = "unmodified"
assault_dam_set_to = "d8"
assault_special = "Cunning[1 for 2]"
assault_ap = ""
orders_gained = [ "Load(2)",]
orders_lost = [ "",]
cost = "1cp"
required_to_buy = "Model: Elite Infantry or Elite Cavalry"
type_ = "Elite Infantry Weapon"
filters = [ "team",]

[weapons."Ork Musket"]
race = "Ork"
name = "Ork Musket"
template = ""
range_ = "3"
angle = "*/*/-/-"
special = ""
damage = "d6-1"
ap = "-2"
assault_mod = ""
assault_deflection_mod = ""
assault_deflection_die_set_to = ""
assault_dam_set_to = ""
assault_special = ""
assault_ap = ""
orders_gained = [ "",]
orders_lost = [ "",]
cost = ""
required_to_buy = ""
type_ = ""
filters = [ "team",]

[units.Grunt]
race = "Ork"
name = "Grunt"
members = "4"
size = "medium"
cost = "2mp"
armor = ""
type_ = "Bio, Grunt, Walks"
isReplacement = ""
replaces = ""
weapons_input = [ "",]
unit_special = "Cannot use ranged weapons"
assault = "2/2/2/2"
assault_die = "6+"
assault_deflection_die = ""
assault_damage = "d6-2"
assault_ap = "-2"
assault_deflection = ""
assault_special = "Any 6 on assult die roll (not assault deflection) count as two success and you get to reroll 3 dice. Each die may be rerolled a maxium of one time. If you get another 6, repeat the process. "
filters = [ "weapons", "team",]

[units."Awakened war hero"]
race = "Ork"
name = "Awakened war hero"
members = "1"
size = "medium"
cost = "N.A. Only comes into play through an Elite ork 'not yet dead' ability"
armor = ""
type_ = "Bio, Infantry, Walks"
isReplacement = ""
replaces = ""
weapons_input = [ "",]
unit_special = "has same orders available as the unit base it awakened from, and the same weapons as the last surviving member of the unit base"
assault = "6/3/3/3"
assault_die = "6+"
assault_deflection_die = "6+"
assault_damage = "d6"
assault_ap = ""
assault_deflection = "2/-/-/-"
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 6 dice Each die may be rerolled a maxium of one time. If you get more 6, repeat the process. \\\\ "
filters = [ "weapons", "team",]

[units.HammerHead]
race = "Ork"
name = "HammerHead"
members = "1"
size = "Large"
cost = "8ip"
armor = "8/3/2/2"
type_ = "Mechanical, Bio Crew, Vehicle, Track"
isReplacement = ""
replaces = ""
weapons_input = [ "Harpoon Gun",]
unit_special = "Has 4 Harpoon Guns which are all fired within same angle-sector when firing"
assault = "12/8/8/8"
assault_die = "6+"
assault_deflection_die = "6+"
assault_damage = "d8+3/d8/d8/d8"
assault_ap = "5/-2/-2/-2"
assault_deflection = "12/2/2/2"
assault_special = "You may reroll up too 3 dice per 6 this unit roll in regular assaults. Each die may be rerolled a maxium of one time. If you get another 6, repeat the process. \\\\ Assault deflection die may not be used to deflect attacks against you, but negate the enemies assault deflection dice instead"
filters = [ "weapons", "team",]

[units."Warg Rider"]
race = "Ork"
name = "Warg Rider"
members = "2"
size = "medium"
cost = "2mp, 4xp"
armor = ""
type_ = "Bio, Cavalry, Elite, Walks"
isReplacement = ""
replaces = ""
weapons_input = [ "",]
unit_special = "May use crafts (both melee and ranges) which uses 1 hand. Fire orders only available if given ranged weapon"
assault = "4/4/4/4"
assault_die = "6+"
assault_deflection_die = "6+"
assault_damage = "d6-2"
assault_ap = ""
assault_deflection = "2/2/1/1"
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice Each die may be rerolled a maxium of one time. If you get another 6, repeat the process. "
filters = [ "weapons", "team",]

[units.Troll]
race = "Ork"
name = "Troll"
members = "1"
size = "Huge"
cost = "16xp"
armor = ""
type_ = "Bio, Monster, Walks"
isReplacement = ""
replaces = ""
weapons_input = [ "",]
unit_special = "May have a maximum of twelve -1 counters to assault damage, and 1 temporarily killed token\\\\ At each aftermath phase, remove/downgrade up to three of the following: one +1 for future damage marker, downgrade one bleeding one step, one -1 counter to assault damage or 1 temporarily killed token.\\\\"
assault = "10/8/6/4"
assault_die = "5+"
assault_deflection_die = ""
assault_damage = "d6+12"
assault_ap = ""
assault_deflection = ""
assault_special = "Reduce damage by 2 for each successfull assault deflection rolled by enemy"
filters = [ "weapons", "team",]

[units.Halftrack]
race = "Ork"
name = "Halftrack"
members = "1"
size = "large"
cost = "4ip"
armor = "2/1/1/1"
type_ = "Mechanical, Bio Crew, Vehicle, Half-Track"
isReplacement = ""
replaces = ""
weapons_input = [ "Heavy MG",]
unit_special = "Bad Shot (-1 to hit) \\\\ May transport up to 2 grunts or 1 infantry. "
assault = "4/3/2/1"
assault_die = "6+"
assault_deflection_die = "6+"
assault_damage = "d6-1"
assault_ap = ""
assault_deflection = "2/-/-/-"
assault_special = "May unload 1 infantry or grunt as part of assault"
filters = [ "weapons", "team",]

[units."Ork Infantry"]
race = "Ork"
name = "Ork Infantry"
members = "4"
size = "medium"
cost = "4mp"
armor = ""
type_ = "Bio, Infantry, Walks"
isReplacement = ""
replaces = ""
weapons_input = [ "Ork Musket",]
unit_special = "Generic Abilities (see general rules) \\\\Bad shot: -1 to hit with ranged weapons. \\\\ Take Cover[stand-still][-2]"
assault = "2/2/2/2"
assault_die = "6+"
assault_deflection_die = ""
assault_damage = "d6-2"
assault_ap = "-2"
assault_deflection = ""
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice. Each die may be rerolled a maxium of one time. If you get another 6, repeat the process. "
filters = [ "weapons", "team",]

[units."Elite Ork Infantry"]
race = "Ork"
name = "Elite Ork Infantry"
members = ""
size = "medium"
cost = "4xp"
armor = ""
type_ = "Bio, Infantry, Elite, Walks"
isReplacement = "yes"
replaces = "Model: Infantry or Grunt"
weapons_input = [ "",]
unit_special = "Unit base gains: Not Yet dead: after all 4 infantry in the unit base are killed, there is one that is not dead et afterall and becomes an {\\it awakened war hero} with the same equipment and orders available as the last infantry killed. Awakened War Hero does not retain any of the abilities from the unit base or the model, and has a seperate unit entry. See War Hero"
assault = "3/2/2/2"
assault_die = "6+"
assault_deflection_die = "6+"
assault_damage = "d6"
assault_ap = "-2"
assault_deflection = "1/-/-/-"
assault_special = "Any 6 on assault die roll (not assault deflection) count as two success and you get to reroll up to 3 dice (identical rules to the original die) (exploding die)"
filters = [ "weapons", "team",]

[units.Grunt.orders]

[units.Grunt.damage_tables]
"Regular damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psychic damage[d6]", "9+: destroy unit base",]
"Psychic damage" = [ "4+: unit base shaken",]

[units."Awakened war hero".orders]
"" = [ "",]

[units."Awakened war hero".damage_tables]
"Regular Damage" = [ "2-3: Bleeding[4]", "4+ : Killed",]

[units.HammerHead.orders]
Fire = [ "(stand still) load + -", "(stand still) load unstable + -", "(all) fire + -",]
Movement = [ "(fast) F+ F + -", "(fast) F + R + -", "(fast) F + L + -", "(fast) F + B + -", "(fast) B + B + -", "(default fast) F + B + B", "(slow) L + - + -", "(slow) L + L + -", "(slow) R + - + -", "(slow) R + R + -", "(slow) A + F + -", "(slow) B + - + -", "(default slow)  - + B + B", "(slow) F + - + -", "(slow) B + rev + -", "(stand still) L + - + -", "(stand still) L + L + -", "(stand still) L + L + L", "(stand still) R + - + -", "(stand still) R + R + -", "(stand still) R + R + R", "(stand still) - + - + -", "(stand still) R + A + F", "(stand still) L + A + F", "(stand still) A + F + -", "(stand still) rev + - + -", "(default stand still) - + - + -", "(stand-still) aim + - + -",]

[units.HammerHead.damage_tables]
"Regular Damage" = [ "1-5: Light damage[d6]", "6-8: Critical Damage, +1 on all future damage", "9+: unit destroyed",]
"Light Damage" = [ "1-3: unit shaken", "4-5: +1 on all future damage", "6: -2/-2/-2/-2 (cumulative) on assault values",]
"Critical damage" = [ "1-3: Light damage[d6], 3 times", "4: Unit cannot rotate Left", "5: Unit Cannot rotate Right", "6: Harpoon guns destroyed.",]

[units."Warg Rider".orders]
"Movement orders" = [ "Fast: 360$^0$ + F + F", "Fast: F + 360$^0$ + F", "Fast: F + F + 360$^0$", "Fast: F + B + 360$^0$", "Slow: 360$^0$ + 360$^0$ + 360$^0$", "Slow: 360$^0$ + A + F",]
"Fire Orders" = [ "load + -", "fire + -", "- + fire",]

[units."Warg Rider".damage_tables]
"Psychic Damage" = [ "5+: unit shaken",]
"Regular Damage" = [ "2-3: Bleeding[6]", "4-5: Bleeding[6], +1 to future damage, psychic damage[d6]", "6+: kill 1 member, psycic damage[d6]",]

[units.Troll.orders]
"Main orders" = [ "- + - + Chase",]

[units.Troll.damage_tables]
"Regular Damage" = [ "1-3: +1 for future damage", "4-6: +1 for future damage, bleed[4]", "7-8: +2 for future damage, bleed[4]", "10-12: +2 for future damage, bleed[6]", "13-15: +3 for future damage, bleed[6]", "16-18: +3 for future damage, bleed[8]", "19-21: +4 for future damage, bleed[8]", "22-24: +4 for future damage, bleed[10], -1 (cumulative) on assault damage", "25-27: +5 for future damage, bleed[12], -2 (cumulative) on assault damage", "28-29: +10 for future damage, bleed[12], -4 (cumulative) on assault damage", "30-99: as 28-29 pluss Troll Momentarily killed", "100+: Troll permanently killed",]

[units.Halftrack.orders]
Fire = [ "Fire (heavy MG) + -", "- + Fire (heavy MG)", "Load(2) + -", "(stand-still or slow) aim + -", "(stand-still or slow) - + aim", "- + Load(2)",]
"Movement orders" = [ "(fast): F + F + F", "(fast): F + F + R", "(fast): F + F + L", "(fast): F + F + Unload", "(stand-still): R + - + -", "(stand-still): L + - + -", "(stand-still): R + R + -", "(stand-still): R + R + R", "(stand-still): L + L + L", "(stand-still) L + L + -", "(stand-still): rev + - + -", "(stand-still): Unload + - + -", "(slow): A + F + R", "A + F + L", "(slow): A + F + -", "(slow): B + - + -", "(slow): B + rev + -", "(slow): L + L + -", "(slow): L + - + -", "(slow): R + R + -", "(slow): R + - + - ", "(slow): F + R + Unload", "(slow): F + L + Unload", "(slow): F + Unload + -",]

[units.Halftrack.damage_tables]
"Light damage" = [ "1-2: +1 on future damage", "3-4: Unit shaken", "5-6: Roll a d6 of regular damage to each transported unit base.",]
"Regular Damage" = [ "1-4: roll on lightly damage [d6]", "5-8: +1 on future damage, roll for critical damage[d6]", "9+: Unit destroyed",]
"Critical damage" = [ "1-2: Unit cannot accelerate any more. ", "3-4: unit cannot brake any more", "5-6: unit gains +1 to be hit and -1 to hit.",]

[units."Ork Infantry".orders]
"Fire Orders" = [ "(stand-still) - + Fire", "(stand-still) Fire + - ", "(stand-still) - + load", "(stand-still) load + -", "(stand-still) - + aim", "(stand-still) aim + - ",]
"Movement Orders" = [ "(slow) 360$^0$ + F + 360$^0$", "(slow) 360$^0$ + 360$^0$ + 360$^0$", "(slow) 360$^0$ + B + -", "(stand-still) 360$^0$ + - + -", "(stand-still) 360$^0$ + A + F", "(slow) - + - + chase",]

[units."Ork Infantry".damage_tables]
"Psychic Damage" = [ "4+: unit base shaken",]
"Regular Damage" = [ "1-5: kill 1 member", "6-8: kill 1 member, roll on psychic damage [d6]", "9+ Destroy Unit Base",]

[units."Elite Ork Infantry".orders]
"" = [ "",]

[units."Elite Ork Infantry".damage_tables]
"" = [ "",]
