[races]

    [races.gnome]
    name = "gnome"


[units]

    [units.gnome_infantry]
    race = "gnome"
    name = "Gnome Infantry"
    models = ["gnome_infantry"]
    size = "medium"
    armor = [0, 0, 0, 0]
    cost.mp = 4
    special = ["Take-Cover[still][-2]"]


        [units.gnome_infantry.orders.movement]
        slow = [["Chase", "", ""],
	     ["", "", "Chase"],
	     ["360°", "F",  "360°"],
	     ["360°", "360°", "360°"],
	     ["360°", "B", "-"]]
	still = [["360°", "-", "-"], ["360°", "A", "F"]]
        default.slow = ["", "", "Flee"]

        [units.gnome_infantry.orders.fire]
	still = [["Load", "-"],
	      ["-", "Load"],
	      ["Fire", "-"],
	      ["-", "Fire"],
	      ["Aim", "-"],
	      ["-", "Aim"]]
	all   = [["fire (reserve)", "fire (reserve)"]]

        [units.gnome_infantry.damage_tables]
        regular = ["1-5: Kill 1 model",
            "6-8: Kill 1 Model, d6 Psychic damage",
            "9: Destroy unit base",
        ]
        psychic = [
            "4+: Unit Shaken",
        ]


    [units.gnome_motorcycle]
    race = "gnome"
    name = "Gnome Motorcyle"
    models = ["gnome_motorcycle"]
    size = "medium"
    armor = [4, 3, 0, 0]
    cost.mp = 2
    cost.xp = 4
    cost.cp = 4
    special = ["Elusive[fast]: additional -1 to be hit while fast"]


        [units.gnome_motorcycle.orders.movement]
	fast = [["F","F","F,B"],
	     ["F","F","360$^0$"],
	     ["360$^0$","F","F"],
	     ["F","360$^0$","F"],
	     ["F","B","360$^0$"]]
	slow = [["360$^0$","F","360$^0$"],
	     ["360$^0$","A","F"],
	     ["360$^0$","F,B","360$^0$"]]
	still = [["360$^0$","A","F"], ["360$^0$","-", "-"]]
	default_still = ["", "", "A,Flee"]  
	default.slow = ["", "", "Flee"]
	default.fast = ["", "Flee", "Flee"]	

        [units.gnome_motorcycle.orders.fire]
	still = [["-", "Load"],
	      ["-", "Fire"]]
	slow = [["-", "Load"],
	      ["-", "Fire"]]
	fast = [["-", "Fire"]]

        [units.gnome_motorcycle.damage_tables]
        regular = ["2-3: +1 on future damge",
            "4+: Kill 1 model"]
     
        psychic = [
            "6+: Unit Shaken",
        ]

    [units.gnome_helicopter]
    race = "gnome"
    name = "Gnome Helicopter"
    models = ["gnome_helicopter"]
    size = "large"
    armor = [0, 0, 0, 0]
    cost.ip = 6
    cost.xp = 2
    special = ["Fires, loads and aim all weapons simultaniously", "Good Shot: +1 to hit or Excelent Shot: +2 to hit if helicopter is hovering still in the air (still flying)."]


        [units.gnome_helicopter.orders.movement]
	still_ground = [["A[still flying]", "360$^0$", "-"], ["A[slow flying]","360$^0$", "F"], ["A[still flying]","360$^0$", "-"]]
	still_flying = [["360$^0$", "-", "-"],["-","-", "D"], ["A[slow flying]", "360$^0$", "F"], ["A[fast flying]", "360$^0$", "F"]]
	slow_flying =[["L","F","-"],
		    ["L","F","L"],
		    ["R","F-"],
		    ["R","F","R"],
		    ["-","-","D"],
		    ["-","R","D"],
		    ["-","L","D"],
		    ["A[fastflying]","F","F"],
		    ["F", "B[stillflying]","360$^0$" ]]
	fast_flying = [["F", "F", "-"],
		    ["F", "F",  "R"],
		    ["F", "F", "L"],
		    ["F", "F", "B[slow flying],360$^0$"],
		    ["F", "F", "B[still flying],360$^0$"]]

	default.still_flying = ["-", "-", "B[still ground]"]
	default.slow_flying = ["-", "-", "B[still ground]"]
	default.fast_flying = ["-", "-", "B[still ground]"]	

        [units.gnome_helicopter.orders.fire]
	still_ground = [["-", "Load"]]
	slow_flying = [["-", "Load"], ["-", "Fire", "-"]]
	fast_flying = [["-", "Load"], ["-", "Fire"]]
	still_flying = [["-", "Load"], ["Aim", "Fire"], ["Fire", "Aim"]]

        [units.gnome_helicopter.damage_tables]
        regular = ["1-4: d6 light damage",
            "5-8: x3 d6 light damge",
            "9: Destroy unit base",
        ]
	light = ["1-4: +1 to future damgage", "5-6: shaken"]
	crew  = ["as regular damage"]

#
# Models
#
[models]

    [models.gnome_infantry]
    name = "Gnome Infantry"
    race = "gnome"
    equipment_limit = ["hands:2", "reserve:1", "independent:∞"]
    equipments = ["gnome_gun", "light_smg" ]
    type = ["bio", "infantry", "walks"]
    special = []

        [models.gnome_infantry.assault]
        strength = [1, 1, 1, 1]
        strength_die = "5+"
        deflection = [0, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = ["Cunning assault[1 for 2]"]

    [models.gnome_motorcycle]
    name = "Gnome Motorcycle"
    race = "gnome"
    equipment_limit = ["motorcycle_weapon:1", "independent:∞"]
    equipments = ["splintbombgrenade_launcher"]
    type = ["bio", "motorcycle", "wheel"]
    special = []

        [models.gnome_motorcycle.assault]
        strength = [2, 1, 1, 0]
        strength_die = "3+"
        deflection = [2, 1, 0, 0]
        deflection_die = "5+"
        damage = "d6-2"
        ap = 2
        special = ["Pre-Assault Retreat[4+]"]

    [models.gnome_helicopter]
    name = "Gnome Helicpoter"
    race = "gnome"
    equipment_limit = ["helicopter_front:1", "helicopter_drop:1", "helicopter_side:1", "independent: ∞"]
    equipments = ["acidic_napalm_bomb", "helicopter_gattling_gun" ]
    type = ["bio_crew", "helicopter", "flying"]
    special = ["Quick fix: In aftermath this unit may either remove one shaken token or one +1 to future damage token"]

        [models.gnome_helicopter.assault]
        strength = [1, 1, 1, 1]
        strength_die = "3+"
        deflection = [1, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = []

    [models.tinkerer_helicopter]
    name = "Gnome Helicpoter"
    race = "gnome"
    equipment_limit = ["helicopter_front:1", "helicopter_drop:1", "helicopter_side:1", "independent: ∞"]
    equipments = ["acidic_napalm_bomb", "helicopter_gattling_gun" ]
    type = ["bio_crew", "helicopter", "flying", "tinkerer"]
    special = ["Improved Quick fix: In aftermath this unit may remove up to two shaken tokens, two +1 to future damage token or one of each"]
    replaces = ["gnome_helicopter"]
    cost.xp = 8
    cost.cp = -4


        [models.tinkerer_helicopter.assault]
        strength = [1, 1, 1, 1]
        strength_die = "3+"
        deflection = [1, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = []


    [models.gnome_elite_infantry]
    name = "Gnome Elite Infantry"
    race = "gnome"
    equipment_limit = ["hands:2", "reserve:∞", "independent:∞"]
    equipments = ["gnome_gun", "light_smg", "poison_dart", "acid_ballon", "grinder" ]
    type = ["bio", "elite", "infantry", "walks"]
    replaces = ["gnome_infantry"]
    special = ["Threat any gunnery phase without any other ordre as fire(reserve) order instead (for this model only.)", "Unit base gains psycic resistance 1 as long as atleast one elite model is alive."]
    cost.xp = 1

    	[models.gnome_elite_infantry.assault]
        strength = [1, 1, 1, 1]
        strength_die = "3+"
        deflection = [0, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = ["Cunning assault[1 for 2]"]

    [models.gnome_tinkerer]
    name = "Gnome Tinkerer"
    race = "gnome"
    equipment_limit = ["hands:2", "reserve:∞", "independent:∞"]
    equipments = ["tinkerer_gun", "light_smg" ]
    type = ["bio", "infantry", "tinkerer", "walks"]
    cost.xp = 4
    cost.cp = -3
    replaces = ["gnome_infantry"]
    special = ["Once per game: May Launch Mechanical Badger: Place a mechanical badger unit in any of the surronding hexes. "]

        [models.gnome_tinkerer.assault]
        strength = [1, 1, 1, 1]
        strength_die = "5+"
        deflection = [0, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = ["Cunning assault[1 for 2]"]


[equipments]

    [equipments.gnome_gun]
    name = "Gnome Gun"
    race = "gnome"
    requires = [
        ["hands:2"],
    ]

        [equipments.gnome_gun.range]
        range = 4
        angle = [true, true, true, true]
        damage = "d6-2"
        ap = 2
        special = []


    [equipments.acid_splash]
    name = "Acid Splash"
    race = "gnome"
    cost.cp = 2
    requires = [
        ["hands:2"],
    ]

        [equipments.acid_splash.range]
        range = 4
        angle = [true, true, true, true]
        damage = "-"
        ap = 0
        special = ["No regular damage", "Minor Acid"]



    [equipments.tinkerer_gun]
    name = "Gnome Gun"
    race = "gnome"
    requires = [
        ["hands:2"],
	["type:infantry"],
	["type:tinkerer"]
    ]

        [equipments.tinkerer_gun.range]
        range = 4
        angle = [true, true, true, true]
        damage = "d6"
        ap = 2
        special = []


    [equipments.light_smg]
    name = "Light SMG"
    race = "gnome"
    requires = [
        ["reserve:1"],
    ]

        [equipments.light_smg.range]
        range = 2
        angle = [true, true, true, true]
        damage = "d4-2"
        ap = 1
        special = ["Reserve weapon: may use this weapon instead of main gun when fire (reserve) orders is given, but you may only use one reserve weapon at any given time.", "Always treated as loaded"]



    [equipments.poison_dart]
    name = "Poison Dart"
    race = "gnome"
    requires = [
        ["reserve:1"],
    ]

        [equipments.poison_dart.range]
        range = 1
        angle = [true, true, true, true]
        damage = "-"
        ap = 0
        special = ["Reserve weapon: may use this weapon instead of main gun when instead of main gun fire (reserve) orders is given, but you may only use one reserve weapon at any given time.", "Always treated as loaded. Poison[4]"]


    [equipments.acid_ballon]
    name = "Acid Ballon"
    race = "gnome"
    requires = [
        ["reserve:1"],
    ]

        [equipments.acid_ballon.range]
        range = 1
        angle = [true, true, true, true]
        damage = "-"
        ap = 0
        special = ["Reserve weapon: may use this weapon instead of main gun when instead of main gun fire (reserve) orders is given, but you may only use one reserve weapon at any given time.", "Always treated as loaded. Minor Acid"]


    [equipments.grinder]
    name = "Grinder"
    race = "gnome"
    requires = [
        ["reserve:1"],
    ]

        [equipments.grinder.range]
        range = 1
        angle = [true, true, true, true]
        damage = "d8-2"
        ap = 2
        special = ["Reserve weapon: may use this weapon instead of main gun when instead of main gun fire (reserve) orders is given, but you may only use one reserve weapon at any given time.", "Only treated as loaded if your main gun is loaded. Minor Acid"]


    [equipments.mechanical_owl]
    name = "Mechanical Owl"
    race = "gnome"
    unit.cost.cp = 2
    special = ["Gives all weapons the enhanced accurazy trait"]
    requires = [["type: infantry"],["independent:1"]]

    [equipments.master_crafted_frost_ray]
    race = "gnome"
    name = "Master Crafted Frost Ray"
    cost.xp = 4
    cost.cp = 2
    requires = [["type: infantry"],["hands:2"]]
    

    	     [equipments.master_crafted_frost_ray.range]
	     range = 4
             angle= [true, true, true, true]
             damage = "d4-2+d6 psycic damge + d4 crew damage"
             ap = 0
	     special = [ "If you use the 'amplified fire' order, and if you hit the enemy unit atleast once, the target must break if possible (if it has a lower speed available). Reduce the speed emidetely"]
	     
	     [equipments.master_crafted_frost_ray.orders_gained.fire]
	     still = ["-", "amplified fire"]


    [equipments.green_gas_launcher]
    race = "gnome"
    name = "Green Gas Launcer"
    model_cost.cp = 2
    requires = [["type: tinkerer", "type: elite"],["type:infantry"],["reserve:1"]]

    	     [equipments.green_gas_launcher.range]
	     range = 3
             angle= [true, true, true, true]
             damage = "d6 psycic damage + d4 crew damage"
             ap = 0
	     special = ["Choose one hex within ragne: Area(5+)", "Poison[4]", "Reserve weapon: may use this weapon instead of main gun when either fire (reserve) orders is given or a regular fire order is given, but you may only use one weapon at any given time.", "Always treated as loaded"]


    [equipments.helicopter_mounted_green_gas_launcher]
    race = "gnome"
    name = "Helicopter mounted Green Gas Launcer"
    cost.cp = 2
    requires = [["type: tinkerer"],["type:helicopter"],["helicopter_side:1"]]

    	     [equipments.helicopter_mounted_green_gas_launcher.range]
	     range = 3
             angle= [true, true, true, true]
             damage = "d6 psycic damage + d4 crew damage"
             ap = 0
	     special = ["Choose one hex within ragne: Area(5+)", "Poison[4]"]


    [equipments.experimental_plasma_gun]
    race = "gnome"
    name = "Experimental Plasma Gun"
    model_cost.cp = 6
    requires = [["type: tinkerer"],["type:infantry"],["hands:2"]]

    	     [equipments.experimental_plasma_gun.range]
	     range = 4
             angle= [true, true, true, true]
             damage = "d12-3"
             ap = 6
	     special = ["If the natural to-hit die is a 1 or 2 (regardless wether you hit or not), the gun explodes causing 1d6 fire damage to the wielder. If this damage causes atleast one model to die, remove the model carring the plasma gun first."]


    [equipments.helicopter_mounted_experimental_plasma_gun]
    race = "gnome"
    name = "Helicopter Mounted Experimental Plasma Gun"
    cost.cp = 6
    requires = [["type: tinkerer"],["type:helicopter"],["helicopter_side:1"]]

    	     [equipments.helicopter_mounted_experimental_plasma_gun.range]
	     range = 6
             angle= [false, true, true, false]
             damage = "d12-3"
             ap = 6
	     special = ["If the natural to-hit die is a 1 or 2 (regardless wether you hit or not), the gun explodes causing 1d6 fire damage to the wielder"]


    [equipments.helicopter_gattling_gun]
    race = "gnome"
    name = "Helicopter Gattling Gun"
    requires = [["type:helicopter"],["helicopter_front:1"]]

    	     [equipments.helicopter_gattling_gun.range]
	     range = 3
             angle= [true, false, false, false]
             damage = "d6-1"
             ap = 6
	     special = [ "Fire once at all enemy units within range and within one angle of fire", "If aim, instead use focus fire, roll 6 dice at same unit base", "Bullet storm: If not using aim, a natural 6 on to-hit die is considered a hit regardless of to-hit modifiers"]


    [equipments.acidic_napalm_bomb]
    race = "gnome"
    name = "Acidic Napalm Bomb"
    requires = [["type:helicopter"],["helicopter_drop:1"]]

    	     [equipments.acidic_napalm_bomb.range]
	     range = 1
             angle= [true, true, true, true]
             damage = "n.a"
             ap = 0
	     special = [ "Choose a hex within range 1: Area(4+): minor acid and set target unit on fire"]



    [equipments.assault_bot_mortar]
    race = "gnome"
    name = "Assault Bot Mortar"
    unit.cost.cp = 6
    requires = [["type:infantry"],["hands:2"]]
    special = ["No regular damage", "When firing, place an assault bot with number of models equal to the number of models firing this weapon (from this unit) in an empty hex within range 4. Requires to be loaded to be used, just as a normal weapon."]


    [equipments.assault_bot_dropper]
    race = "gnome"
    name = "Assault Bot Dropper"
    unit.cost.cp = 2
    requires = [["type:helicopter"],["helicopter_drop:1"]]
    special = ["No regular damage", "When firing, place two assault bot units with 4 models in an empty hex within range 1. Requires to be loaded to be used, just as a normal weapon."]


    [equipments.splintbombgrenade_launcher]
    race = "gnome"
    name = "splintbombgrenade_launcher"
    requires = [["type:motorcycle"],["motorcycle:1"]]

    	     [equipments.splintbombgrenade_launcher.range]
	     range = 2
             angle= [true, true, true, true]
             damage = "d6"
             ap = 2
	     special = ["Choose one hex within range. If fired from 3 models it has Area(4+), if fired from 2 models it has Area(5+), if fired by 1 model it has Area(6+)"]

