[races]

    [races.ork]
    name = "Ork"


[units]

    [units.grunt]
    name = "Grunt"
    race = "ork"
    models = ["grunt", "grunt", "grunt", "grunt"]
    size = "medium"
    cost.mp = 2
    armor = [0, 0, 0, 0]
    special = "Forward Position[2], Cannot use ranged weapons"

        [units.grunt.orders.movement]
        slow = [["Chase", "", ""], ["", "", "Chase"]]
        default.slow = ["", "", "Flee"]

        [units.grunt.damage_tables]
        regular = [
            "1-5: Kill 1 model",
            "6-8: Kill 1 Model, d6 Psychic damage",
            "9: Destroy unit base",
        ]
        psychic = [
            "4+: Unit Shaken",
        ]

    [units.bioengineered_ork]
    name = "BioEngineered Ork"
    race = "ork"
    models = ["bioengineered_ork", "bioengineered_ork", "bioengineered_ork", "bioengineered_ork"]
    size = "medium"
    cost.mp = 4
    cost.xp = 2
    unit_cost.cp = 1
    armor = [0, 0, 0, 0]
    special = [
        "Take Cover[still][-2], May use multiple ranged weapons without any penalties",
        "Poison Resistance 1, Fire Resistance 1, Immunity to Acid",
    ]

        [units.bioengineered_ork.orders.fire]
        still = [["", "Fire"], ["Fire", ""], ["", "Load"], ["Load", ""], ["Aim", ""]]
        all = [["", "Aim"]]

        [units.bioengineered_ork.orders.movement]
        still = [["360°", "", ""], ["360°", "A", "F"]]
        slow = [["360°", "F", "360°"], ["360°", "360°", "360°"], ["360°", "B", ""], ["", "", "Chase"]]
        default.still = ["", "", "A, Flee"]
        default.slow = ["", "", "Flee"]

        [units.bioengineered_ork.damage_tables]
        regular = [
            "1: Bleed[4]",
            "2-5: Kill 1 model",
            "6-8: Kill 1 Model, d6 Psychic damage",
            "9: Destroy unit base",
        ]
        psychic = [
            "5+: Unit Shaken",
        ]

#
# Models
#
[models]

    [models.grunt]
    name = "Grunt"
    race = "ork"
    equipment_limit = ["hands:2", "independent:∞"]
    equipments = []
    type = ["bio", "grunt", "walks"]
    special = []

        [models.grunt.assault]
        strength = [2, 2, 2, 2]
        strength_die = "6+"
        deflection = [0, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = ["{template.ability.reroll_assault:6}", "Cunning assault[1 for 3]"]


    [models.bioengineered_ork]
    name = "BioEngineered Ork"
    race = "ork"
    equipment_limit = ["hands:4", "independent:∞", "shared:1"]
    equipments = ["ork_musket", "ork_musket"]
    type = ["bio", "infantry", "walks"]
    special = []

        [models.bioengineered_ork.assault]
        strength = [3, 2, 2, 2]
        strength_die = "6+"
        deflection = [1, 0, 0, 0]
        deflection_die = "6+"
        damage = "d6-2"
        ap = 2
        special = ["{templates.ability.reroll_assault:6}", "Cunning assault[1 for 2]"]

    [models.elite_bioengineered_ork]
    name = "Elite BioEngineered Ork"
    race = "ork"
    equipment_limit = ["hands:4", "independent:∞"]
    equipments = ["ork_musket", "ork_musket"]
    cost.xp = 1
    type = ["bio", "infantry", "walks", "elite"]
    special = ["Good shot, +1 to hit"]
    replaces = ["bioengineered_ork"]

        [models.elite_bioengineered_ork.assault]
        strength = [4, 3, 3, 3]
        strength_die = "6+"
        deflection = [1, 0, 0, 0]
        deflection_die = "6+"
        damage = "d6-2"
        ap = 2
        special = ["{template.ability.reroll_assault:6}", "Cunning assault[1 for 2]"]


[equipments]

    [equipments.ork_musket]
    name = "Ork Musket"
    race = "ork"
    requires = [
        ["hands:2"],
    ]

        [equipments.ork_musket.range]
        range = 3
        angle = [true, true, false, false]
        damage = "d6-1"
        ap = 2
        special = []

    [equipments.clockwork_shield]
    name = "Clockwork Shield"
    race = "ork"
    special = ["Unit base gains damage resistance 1"]
    unit_cost.cp = 2
    requires = [
        ["type:infantry", "type:grunt"],
        ["hands:1"],
    ]

        [equipments.clockwork_shield.assault]
        deflection.add = [1, 0, 0, 0]
        deflection_die.replace = "6+"

    [equipments.clockwork_wings]
    name = "Clockwork Wings"
    race = "ork"
    unit_cost.cp = 4
    requires = [
        ["type:infantry", "type:grunt"],
        ["independent:1"],
    ]
    special = ["Flies for a short period of time."]

        [equipments.clockwork_wings.assault]
        strength.add = [1, 0, 0, 0]

        [equipments.clockwork_wings.orders_gained.movement]
        slow = [["A(fast, fly)", "Chase", "Chase"]]
        fast_fly = [["Chase", "B(slow, land)", ""]]


    [equipments.flame_covered_axe]
    name = "Flame-covered-axe"
    race = "ork"
    model_cost.cp = 2
    requires = [
        ["type:infantry", "type:cavalry"],
        ["type:elite"],
        ["hands:1"],
    ]

        [equipments.flame_covered_axe.assault]
        damage.replace = "d6+1 + d4 crew damage"
        special.append = ["Fire, Minor Acid[1 for 2], Poison[4][1 for 2]"]


    [equipments.poison_spikes]
    name = "Poison Spikes"
    race = "ork"
    unit_cost.cp = 1
    requires = [
        ["type:infantry", "type:grunt"],
        ["independent:1"]
    ]

        [equipments.poison_spikes.assault]
        special.append = ["Place a poison[4] on any enemy which you deflected an attack from"]


    [equipments.clockwork_monocular]
    name = "Clockwork Monocular"
    race = "ork"
    special = ["Reroll 2 dice in ranged combat per natural 6 rolled for to-hit (regardless of wether that was a hit or not). Each die may be rerolled a maximum of one time (for each wave of rerolls). A new wave of rerolls starts when you get atleast one 6 in the reolled dice."]
    unit_cost.cp = 1
    requires = [
        ["type:infantry"],
        ["independent:1"],
    ]


    [equipments.clockwork_spear]
    name = "Clockwork Spear"
    race = "ork"
    unit_cost.cp = 2
    requires = [
    	     ["type:infantry", "type:grunt", "type:cavalry"],
	     ["hands:1"]
    ]
    	[equipments.clockwork_spear.assault]
	damage.replace = "d8"
	special.append = "Cunning[1 for 2]"


    [equipments.clockwork_power_spear]
    name = "Clockwork Power Spear"
    race = "ork"
    unit_cost.cp = 4
    requires = [
    	     ["type:infantry", "type:grunt"],
	     ["hands:2"]
    ]
    	[equipments.clockwork_power_spear.assault]
	damage.replace = "d12"
	special.append = "Cunning[1 for 2]"
	ap.replace = 3


    [equipments.ork_pistol]
    name = "Ork Pistol"
    race = "ork"
    unit_cost.cp = 1
    requires = [
        ["type:infantry", "type:grunt", "type: cavalery"],
	["hands:1"]
	]


   	[equipments.ork_pistol.range]
	range =3            
	angle = [true, true, false, false]
        damage = "d6-1"
        ap = 2
        special = ["1 handed weapon. Infantry may combine pistol with another 1-handed weapon.", "If combined with another pistol, you may load and fire both pistol simultaniously"]


	[equipments.ork_pistol.orders_gained.fire]
        still = [["Load(2)", "-"], ["-", "Load(2)"]]
        still_slow = [["fire", "-"], ["-", "fire"]]


    [equipments.pyro]
    name = "Pyro"
    race = "ork"
    unit_cost.cp = 4
    cost.xp = 4
    requires = [
        ["type:infantry", "type: cavalery"],
	["independent:1"]
	]


    	[equipments.pyro.range]	
	range =1            
	angle = [true, true, false, false]
        damage = "N.A"
        ap = 0
	special = ["Choose one hex within range, and each model tries to throw one grenade at an enemy in that hex. If enemy base is hit atleast once, that enemy is set on fire.",
	"Don't need to be loaded to be used.",
	"Bonus weapon, can be added to any other combination of weapons, but if you don't have any free hands you must choose between normal weapons and using the pyro grenades",
	"Instead of targeting an enemy unit, you may target the hex you are standing in and place the hex on fire.",
	"In addition, the unit base gains Fire Resistance 2"]


	[equipments.pyro.orders_gained.fire]
        all = [["-", "Throw"]]

    [equipments.hand_held_cannon]
    name = "Hand Held Cannon"
    race = "ork"
    unit_cost.cp = 8
    requires = [
    	     ["type:infantry", "type:grunt", "type: cavalery"],
	     ["shared:1"]
	]

	[equipments.hand_held_cannon.range]		
	range = 4
	angle = [true, false, false, false]
	special = ["Unit base gets the option to fire ONE of this weapon instead of regular weapons."]
	damage = "d6 +3 if penetrating armor"
	ap = 9



	[equipments.war_drum]
	name = "War Drum"
	race = "ork"
	unit_cost.xp = 2
	special = ["Allows any grunt be given (- + - follow) instead of chase. Move each unit with follow orders one step closer to this model.", "Unit Base gains Terror[6][range 1]]"]
	requires = [
		 ["type:infantry"],
		 ["type:elite"],
		 ["independent:1"]]



   [equipments.harpoon_gun]
   name = "Harpoon Gun"
   race = "ork"
   unit_cost.cp = 4
   requires = [
   	    ["type:infantry"],
	    ["shared:1"]
	]

	[equipments.harpoon_gun.range]
	range = 5
	angle = [true, false, false, false]
	damage = "d6-2"
	ap = 2
	special = [
		"Unit base gets the option to fire ONE of this weapon instead of regular weapons.",
		"If one unit-base of size large or smaller is hit by this weapon but not killed, move the target one hex towards you in agony 0 phase. Keep orientation of the unit. If there are multiple hexes which you can move the target to, you may choose where to move the enemy. However you cannot move the unit into an impassable hex, or overcrowded hex if possible. If this is not possible, the unit is shaken instead of moved. If the unit is flying, move the target to the ground instead. If this movement forces the target to move into a hex occupied by you, carry out an assault."]


   [equipments.harpoon_gun_free]
   name = "Harpoon Gun"
   race = "ork"

	[equipments.harpoon_gun_free.range]
	range = 5
	angle = [true, false, false, false]
	damage = "d6-2"
	ap = 2
	special = [
		"Unit base gets the option to fire ONE of this weapon instead of regular weapons.",
		"If one unit-base of size large or smaller is hit by this weapon but not killed, move the target one hex towards you in agony 0 phase. Keep orientation of the unit. If there are multiple hexes which you can move the target to, you may choose where to move the enemy. However you cannot move the unit into an impassable hex, or overcrowded hex if possible. If this is not possible, the unit is shaken instead of moved. If the unit is flying, move the target to the ground instead. If this movement forces the target to move into a hex occupied by you, carry out an assault."]




   [equipments.grenade_sling]
    
   name = "Grenade Sling"
   race = "ork"
   unit.cost.cp = 6	
   requiers =[["type: infantry"],
   	    ["hands:1"]]
	    

   	[equipments.grenade_sling.range]
	range = 3
	angle = [true, true, true, true]
	special = ["Choose one hex within normal range, if fired from a unit with 3-4 models: Area(4+), if fired from a unit with 1-2 modesl: Area(5+)", "If combined with the pyro, the pyro gains standard range of 3 instead of 1.", "It is a 1 handed weapon but may not be combined with another sling"]
	damage = "d6"
	ap = 6



   [equipments.shriek]
   race = "ork"
   name = "Shriek"

	[equipments.shriek.ranye]
	range = 2
	angle = [false, false, true, true]
	special = ["Burst(5) Must have loaded 5 ammo to be fired, but each time it is fired, it's fired 5 times"]
	damage = "d4-2+ d6 psychic damage"
	ap = 2


   [equipments.speed_cannon]
   race = "ork"
   name = "Speed Cannon"

	[euipments.speed_cannon.range]
	range = 2
	angle = [false, false, true, true]
	special = ["Burst(5): Requires 5 ammo to be shot, but each time it is shot, it fires 5 times"]
	damage = "d6+1"
	ap = 6



   [equipments.flamethrower]
   race = "ork"
   name = "Flamethrower"

   	[equipments.flamethrower.range]
	range_ = 1
	angle = [true, false, false, false]
	special = ["Fire at all hexes possible simultaniously: Area(3+) at point blank range, Area(4+) in the hex at long range directly ahead, and Area(5+) for the two hexes which is on long range and on edge of firing arc. ", " Any target unit effected atleast once is set on FIRE. Fireresistance reduces base damage and crew damage from this weapon. ", " Limited Ammo: May be fired a maximum of 3 times. ", " Starts the game with all 3 ammo loaded"]
damage = "d8 fire damage + d4 crew damage"
       ap = 3


   [equipments.rotating_pop_gun]
   race = "ork"
   name = "Rotating Pop Gun"

   	[equipments.rotating_pop_gun.range]
	range_ = 4
	angle = [true, true, true, true]
	special = "Poison 6"
	damage = "d6 + (d6 crew damage when penetrating all armor)"
	ap = 6


   [equipments.heavy_forward_gun]
   race = "ork"
   name = "Heavy Forward Gun"

   	[equipments.heavy_forward_gun.range]
	range_ = 5
	angle = [true, false, false, false]
	damage = "d6 + 3 if penetrating all armor"
	ap = 7

   [equipments.tanksscalper]
   race = "ork"
   name = "Tanksscalper"
   unit.cost.cp = 2
   requiers = [["type: infantry", "type: grunt"],["hands: 1"]]
   

   	[equipments.tanksscalper.assault]
	assault_special = ["May replace regular damage with d4-2 crew damage. If so, any supporting damage to this damage die adds +1 to crew damage instead of +1 to regular damage. It should be noted that other models within the same unit MAY choose different damage types. Thus only the hit and corresponding supporting hits versus a tank should be converted to crew damage. ", " You loose Cunning Assault if any"]


   [equipments."Healing Syringe"]
   race = "ork"
   name = "Healing Syringe"
   unit.cost.cp = 1
   special = ["In 2nd gunnery phase you may replace any ONE bleeding token on any unit in this hex with a Poison[4] token."]
   requiers = [["type:infantry", "type: cavalry", "type: grunt"], ["hands: 1"]]


   [equipments.assault_musket]
   race = "ork"
   name = "Assault Musket"
   unit.cost.cp = 2
   requiers = [["type: infantry"], ["hands: 2"]]

   	[equipments.assault_musket]
	range_ = 2	
	angle = [true, true, true, true]
	special = ["May have up to 4 ammo stored. Enhanced Accurazy: unit gain +1 to hit (but only when firing this weapon)", " If you have 4 ammo stored, you may spend all 4 ammo to use the 'heavy shot' seting when firing a shot. If you do gain range: 4, AP:3 and damage:d6-1", "ps! It is nor recommended combining this with other ranged weapons as a ork pistol. However if you do, track ammo and loading actions etc. for the other gun and this weapon seperately"]
	damage = "d6-2"
	ap = 2

        [equipments.assault_musket.fire]
        still = [["", "load(2)"],["load(2)", ""]
	all   = [["fire", "fire"]



   [equipments.hand_catapult]
   race = ork
   name = "Hand Catapult"
   unit.cost.cp = 9
   requirs = [["type: infantry"], ["hands:3"]]

       [equipments.hand_catapult.range]
       range_ = 6
       angle = [true, true, true, true]
       special = ["Choose one hex within normal range or one hex within long range. If fired from a unit with 3-4 models within normal range: Area(4+), if fired from a unit with 1-2 models at normal range: Area(5+), if fired from a unit withh 3-4 models within long range: Area(5+), if fired from a unit with 1-2 models within long range: Area(6+)"]
       damage = "d6"
       ap = 6



