[races]

    [races.ork]
    name = "Ork"


[units]

    [units.grunt]
    name = "Grunt"
    race = "ork"
    models = ["grunt", "grunt", "grunt", "grunt"]
    size = "medium"
    cost.mp = 2
    armor = [0, 0, 0, 0]
    equipment_limit = ["weapon.unit_base:1"]
    special = "Forward Position[2], Cannot use ranged weapons"

        [units.grunt.orders.movement]
        slow = [["Chase", "", ""], ["", "", "Chase"]]
        default.slow = ["", "", "Flee"]

        [units.grunt.damage_tables]
        regular = [
            "1-5: Kill 1 model",
            "6-8: Kill 1 Model, d6 Psychic damage",
            "9: Destroy unit base",
        ]
        psychic = [
            "4+: Unit Shaken",
        ]

    [units.bioengineered_ork]
    name = "BioEngineered Ork"
    race = "ork"
    models = ["bioengineered_ork", "bioengineered_ork", "bioengineered_ork", "bioengineered_ork"]
    size = "medium"
    cost.mp = 4
    cost.xp = 2
    cost.cp = 1
    armor = [0, 0, 0, 0]
    special = [
        "Take Cover[still][-2], May use multiple ranged weapons without any penalties",
        "Poison Resistance 1, Fire Resistance 1, Immunity to Acid",
    ]

        [units.bioengineered_ork.orders.fire]
        still = [["", "Fire"], ["Fire", ""], ["", "Load"], ["Load", ""], ["Aim", ""]]
        all = [["", "Aim"]]

        [units.bioengineered_ork.orders.movement]
        still = [["360°", "", ""], ["360°", "A", "F"]]
        slow = [["360°", "F", "360°"], ["360°", "360°", "360°"], ["360°", "B", ""], ["", "", "Chase"]]
        default.still = ["", "", "A, Flee"]
        default.slow = ["", "", "Flee"]

        [units.bioengineered_ork.damage_tables]
        regular = [
            "1: Bleed[4]",
            "2-5: Kill 1 model",
            "6-8: Kill 1 Model, d6 Psychic damage",
            "9: Destroy unit base",
        ]
        psychic = [
            "5+: Unit Shaken",
        ]

#
# Models
#
[models]

    [models.grunt]
    name = "Grunt"
    race = "ork"
    equipment_limit = ["hands:2", "independent:∞"]
    equipments = []
    type = ["bio", "grunt", "walks"]
    special = []

        [models.grunt.assault]
        strength = [2, 2, 2, 2]
        strength_die = "6+"
        deflection = [0, 0, 0, 0]
        deflection_die = ""
        damage = "d6-2"
        ap = 2
        special = ["{template.ability.reroll_assault:6}", "Cunning assault[1 for 3]"]


    [models.bioengineered_ork]
    name = "BioEngineered Ork"
    race = "ork"
    equipment_limit = ["hands:4", "independent:∞", "shared:1"]
    equipments = ["ork_musket", "ork_musket"]
    type = ["bio", "infantry", "walks"]
    special = []

        [models.bioengineered_ork.assault]
        strength = [3, 2, 2, 2]
        strength_die = "6+"
        deflection = [1, 0, 0, 0]
        deflection_die = "6+"
        damage = "d6-2"
        ap = 2
        special = ["{templates.ability.reroll_assault:6}", "Cunning assault[1 for 2]"]

    [models.elite_bioengineered_ork]
    name = "Elite BioEngineered Ork"
    race = "ork"
    equipment_limit = ["hands:4", "independent:∞"]
    equipments = ["ork_musket", "ork_musket"]
    cost.xp = 1
    type = ["bio", "infantry", "walks", "elite"]
    special = ["Good shot, +1 to hit"]
    replaces = ["bioengineered_ork"]

        [models.elite_bioengineered_ork.assault]
        strength = [4, 3, 3, 3]
        strength_die = "6+"
        deflection = [1, 0, 0, 0]
        deflection_die = "6+"
        damage = "d6-2"
        ap = 2
        special = ["{template.ability.reroll_assault:6}", "Cunning assault[1 for 2]"]


[equipments]

    [equipments.ork_musket]
    name = "Ork Musket"
    race = "ork"
    requires = [
        ["hands:2"],
    ]

        [equipments.ork_musket.range]
        range = 3
        angle = [true, true, false, false]
        damage = "d6-1"
        ap = 2
        special = []

    [equipments.clockwork_shield]
    name = "Clockwork Shield"
    race = "ork"
    special = ["Unit base gains damage resistance 1"]
    unit_cost.cp = 2
    requires = [
        ["type:infantry", "type:grunt"],
        ["hands:1"],
    ]

        [equipments.clockwork_shield.assault]
        deflection.add = [1, 0, 0, 0]
        deflection_die.replace = "6+"

    [equipments.clockwork_wings]
    name = "Clockwork Wings"
    race = "ork"
    unit_cost.cp = 4
    requires = [
        ["type:infantry", "type:grunt"],
        ["independent:1"],
    ]
    special = ["Flies for a short period of time."]

        [equipments.clockwork_wings.assault]
        strength.add = [1, 0, 0, 0]

        [equipments.clockwork_wings.orders_gained.movement]
        slow = [["A(fast, fly)", "Chase", "Chase"]]
        fast_fly = [["Chase", "B(slow, land)", ""]]


    [equipments.flame_covered_axe]
    name = "Flame-covered-axe"
    race = "ork"
    model_cost.cp = 2
    requires = [
        ["type:infantry", "type:cavalry"],
        ["type:elite"],
        ["hands:1"],
    ]

        [equipments.flame_covered_axe.assault]
        damage.replace = "d6+1 + d4 crew damage"
        special.append = ["Fire, Minor Acid[1 for 2], Poison[4][1 for 2]"]


    [equipments.poison_spikes]
    name = "Poison Spikes"
    race = "ork"
    unit_cost.cp = 1
    requires = [
        ["type:infantry", "type:grunt"],
        ["independent:1"]
    ]

        [equipments.poison_spikes.assault]
        special.append = ["Place a poison[4] on any enemy which you deflected an attack from"]


    [equipments.clockwork_monocular]
    name = "Clockwork Monocular"
    race = "ork"
    special = ["Reroll 2 dice in ranged combat per natural 6 rolled for to-hit (regardless of wether that was a hit or not). Each die may be rerolled a maximum of one time (for each wave of rerolls). A new wave of rerolls starts when you get atleast one 6 in the reolled dice."]
    unit_cost.cp = 1
    requires = [
        ["type:infantry"],
        ["independent:1"],
    ]
